# Copyright 2026 Quanscient Oy
# SPDX-License-Identifier: Apache-2.0

# pyright: reportUnusedImport=false

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("allsolve")
except PackageNotFoundError:
    __version__ = "unknown"

__all__ = [
    "__version__",
    # project
    "Project",
    "GeometryPipelineVersion",
    # geometry
    "Geometry",
    "GeometryElement",
    "CadGeometryElement",
    "GDS2ImportConfig",
    "GDSAbsoluteLayer",
    "GDSStackedLayer",
    "GDSUnit",
    "GeometryBuilder",
    "CadElement",
    "CadBox",
    "CadCylinder",
    "CadSphere",
    "CadCone",
    "CadTorus",
    "CadSurfaceRectangle",
    "CadPoint",
    "CadStepFile",
    "CadIgesFile",
    "CadSatFile",
    "CadBrepFile",
    "CadMshFile",
    "CadNasFile",
    "CadGds2File",
    "CadGdsLayer",
    "CadGdsExtrudeParameters",
    "CadGeometryType",
    "CadUnion",
    "CadDifference",
    "CadIntersection",
    "CadFragments",
    "CadFragmentAll",
    "CadTranslate",
    "CadRotate",
    "CadGrid",
    "CadRemove",
    "CadDisk",
    "CadRectangle",
    "CadAlignment",
    "CadPath",
    "CadGlob",
    # mesh
    "Mesh",
    "MeshInstance",
    "MeshSettings",
    "MeshDensity",
    "MeshQuality",
    "MeshRefinement",
    "MeshExtrusion",
    "SlantedExtrusion",
    "PathExtrusion",
    "FlattenAndRebuildExtrusion",
    "ExtrusionLayerDefinition",
    "AutoTransfiniteGroup",
    # simulation
    "Simulation",
    "Script",
    "FieldInitialization",
    "CustomSection",
    "DisableableSection",
    "Runtime",
    "CPU",
    "SolverMode",
    "TimestepAlgorithm",
    "AnalysisType",
    "SimulationOutputData",
    "CsvExportFormat",
    # region
    "Region",
    "RegionRule",
    "KeyValueAttributePath",
    "ComputedRegion",
    "RegionOperation",
    # file
    "delete_file",
    # errors
    "JobError",
    "NotInitializedError",
    "NotProjectAPIKeyError",
    "DeletedError",
    # client
    "Client",
    # api
    "setup",
    "is_setup",
    "is_project_api_key",
    "get_cache_dir",
    "clean_cache",
    # quota
    "get_quota",
    # job
    "Job",
    "OnError",
    # material
    "Material",
    "MaterialProperty",
    # physics
    "Physics",
    "Output",
    "Physic",
    "Field",
    "Fields",
    "Interaction",
    "InteractionParameter",
    "OutputInteraction",
    "Expression",
    "ScalarValue",
    "VectorValue",
    "MatrixValue",
    "BooleanValue",
    "vector_to_str",
    "matrix_to_str",
    "boolean_to_str",
    "vector_from_str",
    "matrix_from_str",
    "boolean_from_str",
    # enums (from .physics.generated.enums)
    "AcousticWavesAcousticExtrapolationTargetShape",
    "AcousticWavesAcousticExtrapolationTimeAggregationDataOperation",
    "AcousticWavesAcousticExtrapolationTimeAggregationOperation",
    "AcousticWavesPeriodicityType",
    "AcousticWavesPmlType",
    "CurrentFlowLumpActuationMode",
    "CurrentFlowLumpVICutActuationMode",
    "CurrentFlowPeriodicityType",
    "ElasticWavesLumpActuationMode",
    "ElasticWavesPeriodicityType",
    "ElasticWavesPmlType",
    "ElectromagneticWavesEigenmodePortTargetEigenvalueType",
    "ElectromagneticWavesLumpVIActuationMode",
    "ElectromagneticWavesPeriodicityType",
    "ElectromagneticWavesPmlType",
    "ElectromagneticWavesRectangularPortModeType",
    "ElectrostaticsLumpActuationMode",
    "ElectrostaticsPeriodicityType",
    "FieldOutputFilterType",
    "FieldStateFilterType",
    "HeatFluidPeriodicityType",
    "HeatTransferLumpTPhiActuationMode",
    "HeatTransferPeriodicityType",
    "LaminarFlowLumpPMActuationMode",
    "LaminarFlowLumpVFvActuationMode",
    "LaminarFlowPressurePeriodicityType",
    "LaminarFlowVelocityPeriodicityType",
    "MagnetismAPeriodicityType",
    "MagnetismHPeriodicityType",
    "MagnetismPhiLumpIVActuationMode",
    "MagnetismPhiLumpPhiPhiBActuationMode",
    "MagnetismPhiPeriodicityType",
    "MeshDeformationPeriodicityType",
    "SolidMechanicsLumpActuationMode",
    "SolidMechanicsPeriodicityType",
    # expression
    "SharedExpression",
    "ExpressionType",
    "ExpressionArg",
    "Variable",
    "Function",
    "InterpolatedFunction",
    # import/export
    "import_project",
    "export_project_data",
    "FileOverwriteMode",
    # override
    "VariableOverrides",
    # from allsolve_rawapi
    "ExpressionBoundingBox",
    "ExpressionVector",
    "InputFile",
    "SimulationInputFile",
    "SimulationInputFileType",
    "SimulationInputFileUpdateResponse",
    "GeometryUnit",
    "SharedExpressionOverrideType",
    "ExtrusionOverlapMode",
    "MeshExtrusionType",
    "SweepType",
    "CadDistanceUnit",
    "CadGdsUnifyLayerDiscretizations",
    "CadSplineMethod",
    "FieldInitializationType",
    "OrganizationQuota",
    "ProjectTypeFilter",
]

from .project import Project, GeometryPipelineVersion
from .geometry import (
    Geometry,
    GeometryElement,
    CadGeometryElement,
    GDS2ImportConfig,
    GDSAbsoluteLayer,
    GDSStackedLayer,
    GDSUnit,
    GeometryBuilder,
    CadElement,
    CadBox,
    CadCylinder,
    CadSphere,
    CadCone,
    CadTorus,
    CadSurfaceRectangle,
    CadStepFile,
    CadIgesFile,
    CadSatFile,
    CadBrepFile,
    CadMshFile,
    CadNasFile,
    CadGds2File,
    CadGdsLayer,
    CadGdsExtrudeParameters,
    CadGeometryType,
    CadUnion,
    CadDifference,
    CadIntersection,
    CadFragments,
    CadFragmentAll,
    CadTranslate,
    CadRotate,
    CadGrid,
    CadRemove,
    CadDisk,
    CadRectangle,
    CadPath,
    CadGlob,
    CadPoint,
)
from .mesh import (
    Mesh,
    MeshInstance,
    MeshSettings,
    MeshDensity,
    MeshQuality,
    MeshRefinement,
    AutoTransfiniteGroup,
    MeshExtrusion,
    SlantedExtrusion,
    PathExtrusion,
    FlattenAndRebuildExtrusion,
    ExtrusionLayerDefinition,
)
from .simulation import (
    Simulation,
    Script,
    FieldInitialization,
    CustomSection,
    DisableableSection,
    Runtime,
    CPU,
    SolverMode,
    TimestepAlgorithm,
    AnalysisType,
    SimulationOutputData,
    CsvExportFormat,
)
from .region import (
    Region,
    RegionRule,
    KeyValueAttributePath,
    ComputedRegion,
    RegionOperation,
)
from .file import delete_file
from .util import JobError, NotInitializedError, NotProjectAPIKeyError, DeletedError
from .client import Client
from .api import setup, is_setup, is_project_api_key, get_cache_dir, clean_cache
from .quota import get_quota
from .job import Job, OnError
from .material import Material, MaterialProperty
from .physics import (
    Physics,
    Output,
    Physic,
    Field,
    Fields,
    Interaction,
    InteractionParameter,
    OutputInteraction,
    # Parameter type aliases and conversion utilities
    Expression,
    ScalarValue,
    VectorValue,
    MatrixValue,
    BooleanValue,
    vector_to_str,
    matrix_to_str,
    boolean_to_str,
    vector_from_str,
    matrix_from_str,
    boolean_from_str,
)

from .physics.generated.enums import *  # noqa: F401, F403
from .expression import (
    SharedExpression,
    ExpressionType,
    ExpressionArg,
    Variable,
    Function,
    InterpolatedFunction,
)
from .import_project import import_project
from .export_project import export_project_data
from .util import FileOverwriteMode
from .override import VariableOverrides

from allsolve_rawapi import (
    ExpressionBoundingBox,
    ExpressionVector,
    InputFile,
    SimulationInputFile,
    SimulationInputFileType,
    SimulationInputFileUpdateResponse,
    GeometryUnit,
    SharedExpressionOverrideType,
    ExtrusionOverlapMode,
    MeshExtrusionType,
    SweepType,
    CadAlignment,
    CadDistanceUnit,
    CadGdsUnifyLayerDiscretizations,
    CadSplineMethod,
    FieldInitializationType,
    OrganizationQuota,
    ProjectTypeFilter,
)
