# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AnalysisType(str, Enum):
    """
    Simulation analysis type
    """

    """
    allowed enum values
    """
    STEADYSTATE = 'steadyState'
    HARMONIC = 'harmonic'
    MULTIHARMONIC = 'multiharmonic'
    TRANSIENT = 'transient'
    EIGENMODE = 'eigenmode'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnalysisType from a JSON string"""
        return cls(json.loads(json_str))


