# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.cad_gds_import_config import CadGdsImportConfig
from allsolve_rawapi.models.cad_vector import CadVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadImportConfig(BaseModel):
    """
    Parameters for importing a STEP, IGES, BREP or SAT file into a 3D model
    """ # noqa: E501
    cleanup: StrictBool = Field(description="Should the imported file be cleaned up for entities that are not bound to geodim level entities. Eg. surfaces that are not part of volume are removed.")
    offset: Optional[CadVector] = None
    gds_import_config: Optional[CadGdsImportConfig] = Field(default=None, alias="gdsImportConfig")
    __properties: ClassVar[List[str]] = ["cleanup", "offset", "gdsImportConfig"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadImportConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of offset
        if self.offset:
            _dict['offset'] = self.offset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gds_import_config
        if self.gds_import_config:
            _dict['gdsImportConfig'] = self.gds_import_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadImportConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cleanup": obj.get("cleanup"),
            "offset": CadVector.from_dict(obj["offset"]) if obj.get("offset") is not None else None,
            "gdsImportConfig": CadGdsImportConfig.from_dict(obj["gdsImportConfig"]) if obj.get("gdsImportConfig") is not None else None
        })
        return _obj


