# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from allsolve_rawapi.models.cad_angle import CadAngle
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadEulerAngles(BaseModel):
    """
    Rotation along x, y and z axis
    """ # noqa: E501
    x: CadAngle
    y: CadAngle
    z: CadAngle
    __properties: ClassVar[List[str]] = ["x", "y", "z"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadEulerAngles from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of x
        if self.x:
            _dict['x'] = self.x.to_dict()
        # override the default output from pydantic by calling `to_dict()` of y
        if self.y:
            _dict['y'] = self.y.to_dict()
        # override the default output from pydantic by calling `to_dict()` of z
        if self.z:
            _dict['z'] = self.z.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadEulerAngles from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "x": CadAngle.from_dict(obj["x"]) if obj.get("x") is not None else None,
            "y": CadAngle.from_dict(obj["y"]) if obj.get("y") is not None else None,
            "z": CadAngle.from_dict(obj["z"]) if obj.get("z") is not None else None
        })
        return _obj


