# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_attribute import CadAttribute
from allsolve_rawapi.models.cad_path_segment import CadPathSegment
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadEntity(BaseModel):
    """
    Entity for the geometric element.
    """ # noqa: E501
    tag: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Tag for the geometric element selection.")
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Name for the geometric element selection.")
    path: Optional[Annotated[List[CadPathSegment], Field(min_length=1)]] = Field(default=None, description="Path for the geometric element.")
    attribute: Optional[CadAttribute] = None
    __properties: ClassVar[List[str]] = ["tag", "name", "path", "attribute"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in path (list)
        _items = []
        if self.path:
            for _item_path in self.path:
                if _item_path:
                    _items.append(_item_path.to_dict())
            _dict['path'] = _items
        # override the default output from pydantic by calling `to_dict()` of attribute
        if self.attribute:
            _dict['attribute'] = self.attribute.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tag": obj.get("tag"),
            "name": obj.get("name"),
            "path": [CadPathSegment.from_dict(_item) for _item in obj["path"]] if obj.get("path") is not None else None,
            "attribute": CadAttribute.from_dict(obj["attribute"]) if obj.get("attribute") is not None else None
        })
        return _obj


