# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_distance import CadDistance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadGdsLayer(BaseModel):
    """
    GDS2 extrusion layer description
    """ # noqa: E501
    id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The layer identifier")
    layer: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="GDSII layer number ")
    type: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="GDSII datatype/texttype number ")
    previous_layer_index: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The optional index of the previous layer in the GDS layer stack. The index refers to the 0-based index of the layer in the array of layers (see CadGDSImportConfig.layers). If left out, either the absoluteZ0 value or 0-value (GDS file z-offset) is used for z0 coordinate. ", alias="previousLayerIndex")
    absolute_z0: Optional[CadDistance] = Field(default=None, alias="absoluteZ0")
    thickness: CadDistance
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Name for the geometric element selection.")
    __properties: ClassVar[List[str]] = ["id", "layer", "type", "previousLayerIndex", "absoluteZ0", "thickness", "name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadGdsLayer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of absolute_z0
        if self.absolute_z0:
            _dict['absoluteZ0'] = self.absolute_z0.to_dict()
        # override the default output from pydantic by calling `to_dict()` of thickness
        if self.thickness:
            _dict['thickness'] = self.thickness.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadGdsLayer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "layer": obj.get("layer"),
            "type": obj.get("type"),
            "previousLayerIndex": obj.get("previousLayerIndex"),
            "absoluteZ0": CadDistance.from_dict(obj["absoluteZ0"]) if obj.get("absoluteZ0") is not None else None,
            "thickness": CadDistance.from_dict(obj["thickness"]) if obj.get("thickness") is not None else None,
            "name": obj.get("name")
        })
        return _obj


