# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_distance import CadDistance
from allsolve_rawapi.models.cad_gds_extrude_parameters import CadGdsExtrudeParameters
from allsolve_rawapi.models.cad_gds_layer import CadGdsLayer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadGdsImportConfig(BaseModel):
    """
    Parameters for importing a GDS2 file into a 3D model
    """ # noqa: E501
    layers: Annotated[List[CadGdsLayer], Field(min_length=1)] = Field(description="Layer definitions for the GDS2 extrusion")
    included_top_level_cells: Optional[List[StrictStr]] = Field(default=None, description="List of included top-level cell names in the GDS2 file. Leave it out or empty to include all.", alias="includedTopLevelCells")
    z_offset: Optional[CadDistance] = Field(default=None, alias="zOffset")
    extrude_parameters: Optional[CadGdsExtrudeParameters] = Field(default=None, alias="extrudeParameters")
    __properties: ClassVar[List[str]] = ["layers", "includedTopLevelCells", "zOffset", "extrudeParameters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadGdsImportConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in layers (list)
        _items = []
        if self.layers:
            for _item_layers in self.layers:
                if _item_layers:
                    _items.append(_item_layers.to_dict())
            _dict['layers'] = _items
        # override the default output from pydantic by calling `to_dict()` of z_offset
        if self.z_offset:
            _dict['zOffset'] = self.z_offset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of extrude_parameters
        if self.extrude_parameters:
            _dict['extrudeParameters'] = self.extrude_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadGdsImportConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "layers": [CadGdsLayer.from_dict(_item) for _item in obj["layers"]] if obj.get("layers") is not None else None,
            "includedTopLevelCells": obj.get("includedTopLevelCells"),
            "zOffset": CadDistance.from_dict(obj["zOffset"]) if obj.get("zOffset") is not None else None,
            "extrudeParameters": CadGdsExtrudeParameters.from_dict(obj["extrudeParameters"]) if obj.get("extrudeParameters") is not None else None
        })
        return _obj


