# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.cad_angle import CadAngle
from allsolve_rawapi.models.cad_distance import CadDistance
from allsolve_rawapi.models.cad_gds_unify_layer_discretizations import CadGdsUnifyLayerDiscretizations
from allsolve_rawapi.models.cad_positive_integer import CadPositiveInteger
from allsolve_rawapi.models.cad_scalar import CadScalar
from allsolve_rawapi.models.cad_spline_method import CadSplineMethod
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadGdsExtrudeParameters(BaseModel):
    """
    Optional parameters for GDS extrusion process. If not specified, default values are used: - unifyLayerDiscretizations: Default before - fuzzyValue: Uses the GDS file precision (default: from importResult.precision) - featureAngleThreshold: Default 30.0 degrees - lengthRatioThreshold: Default 5.0 - splineMethod: Default iterative - splineTolerance: Default 1e-4 millimeters - circleMaxArcAnglePerSegment: Default 360/64 = 5.625 degrees - circleFitToleranceFraction: Default 200 (tolerance = radius / 200) - iterativeMaxIterations: Default 5 
    """ # noqa: E501
    unify_layer_discretizations: Optional[CadGdsUnifyLayerDiscretizations] = Field(default=None, alias="unifyLayerDiscretizations")
    fuzzy_value: Optional[CadDistance] = Field(default=None, alias="fuzzyValue")
    feature_angle_threshold: Optional[CadAngle] = Field(default=None, alias="featureAngleThreshold")
    length_ratio_threshold: Optional[CadScalar] = Field(default=None, alias="lengthRatioThreshold")
    spline_method: Optional[CadSplineMethod] = Field(default=None, alias="splineMethod")
    spline_tolerance: Optional[CadDistance] = Field(default=None, alias="splineTolerance")
    circle_max_arc_angle_per_segment: Optional[CadAngle] = Field(default=None, alias="circleMaxArcAnglePerSegment")
    circle_fit_tolerance_fraction: Optional[CadScalar] = Field(default=None, alias="circleFitToleranceFraction")
    iterative_max_iterations: Optional[CadPositiveInteger] = Field(default=None, alias="iterativeMaxIterations")
    __properties: ClassVar[List[str]] = ["unifyLayerDiscretizations", "fuzzyValue", "featureAngleThreshold", "lengthRatioThreshold", "splineMethod", "splineTolerance", "circleMaxArcAnglePerSegment", "circleFitToleranceFraction", "iterativeMaxIterations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadGdsExtrudeParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fuzzy_value
        if self.fuzzy_value:
            _dict['fuzzyValue'] = self.fuzzy_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of feature_angle_threshold
        if self.feature_angle_threshold:
            _dict['featureAngleThreshold'] = self.feature_angle_threshold.to_dict()
        # override the default output from pydantic by calling `to_dict()` of length_ratio_threshold
        if self.length_ratio_threshold:
            _dict['lengthRatioThreshold'] = self.length_ratio_threshold.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spline_tolerance
        if self.spline_tolerance:
            _dict['splineTolerance'] = self.spline_tolerance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of circle_max_arc_angle_per_segment
        if self.circle_max_arc_angle_per_segment:
            _dict['circleMaxArcAnglePerSegment'] = self.circle_max_arc_angle_per_segment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of circle_fit_tolerance_fraction
        if self.circle_fit_tolerance_fraction:
            _dict['circleFitToleranceFraction'] = self.circle_fit_tolerance_fraction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of iterative_max_iterations
        if self.iterative_max_iterations:
            _dict['iterativeMaxIterations'] = self.iterative_max_iterations.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadGdsExtrudeParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unifyLayerDiscretizations": obj.get("unifyLayerDiscretizations"),
            "fuzzyValue": CadDistance.from_dict(obj["fuzzyValue"]) if obj.get("fuzzyValue") is not None else None,
            "featureAngleThreshold": CadAngle.from_dict(obj["featureAngleThreshold"]) if obj.get("featureAngleThreshold") is not None else None,
            "lengthRatioThreshold": CadScalar.from_dict(obj["lengthRatioThreshold"]) if obj.get("lengthRatioThreshold") is not None else None,
            "splineMethod": obj.get("splineMethod"),
            "splineTolerance": CadDistance.from_dict(obj["splineTolerance"]) if obj.get("splineTolerance") is not None else None,
            "circleMaxArcAnglePerSegment": CadAngle.from_dict(obj["circleMaxArcAnglePerSegment"]) if obj.get("circleMaxArcAnglePerSegment") is not None else None,
            "circleFitToleranceFraction": CadScalar.from_dict(obj["circleFitToleranceFraction"]) if obj.get("circleFitToleranceFraction") is not None else None,
            "iterativeMaxIterations": CadPositiveInteger.from_dict(obj["iterativeMaxIterations"]) if obj.get("iterativeMaxIterations") is not None else None
        })
        return _obj


