# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_alignment import CadAlignment
from allsolve_rawapi.models.cad_euler_angles import CadEulerAngles
from allsolve_rawapi.models.cad_scalar import CadScalar
from allsolve_rawapi.models.cad_vector import CadVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadRectangle(BaseModel):
    """
    Rectangle geometry, 2 dimension element
    """ # noqa: E501
    alignment: Optional[CadAlignment] = CadAlignment.CENTER
    position: CadVector
    size: CadVector
    rotation: Optional[CadEulerAngles] = None
    transform: Optional[Annotated[List[CadScalar], Field(min_length=16, max_length=16)]] = Field(default=None, description="4x4 affine transform matrix as an array of 16 numbers for affine transforming entities")
    __properties: ClassVar[List[str]] = ["alignment", "position", "size", "rotation", "transform"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadRectangle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rotation
        if self.rotation:
            _dict['rotation'] = self.rotation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in transform (list)
        _items = []
        if self.transform:
            for _item_transform in self.transform:
                if _item_transform:
                    _items.append(_item_transform.to_dict())
            _dict['transform'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadRectangle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alignment": obj.get("alignment") if obj.get("alignment") is not None else CadAlignment.CENTER,
            "position": CadVector.from_dict(obj["position"]) if obj.get("position") is not None else None,
            "size": CadVector.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "rotation": CadEulerAngles.from_dict(obj["rotation"]) if obj.get("rotation") is not None else None,
            "transform": [CadScalar.from_dict(_item) for _item in obj["transform"]] if obj.get("transform") is not None else None
        })
        return _obj


