# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_entity import CadEntity
from allsolve_rawapi.models.cad_grid_parameters import CadGridParameters
from allsolve_rawapi.models.cad_rotate_parameters import CadRotateParameters
from allsolve_rawapi.models.cad_scalar import CadScalar
from allsolve_rawapi.models.cad_translate_parameters import CadTranslateParameters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadTransformOperation(BaseModel):
    """
    Applies a geometric transformation operation of *type* for the entities listed in the *target* property. **REMOVE**   Removes entities from the model. **TRANSLATE**   Translates (moves) entities inside the model. See *translate* property for parameters. **ROTATE**   Rotates entities around an axis. See *rotate* property for parameters. **AFFINE**   Affine transforms the entities. See *affine* property for parameters. **GRID**   Creates a grid pattern of the entities. See *grid* property for parameters. 
    """ # noqa: E501
    target: List[CadEntity] = Field(description="Required geometric entities for the operation")
    translate: Optional[CadTranslateParameters] = None
    rotate: Optional[CadRotateParameters] = None
    affine: Optional[Annotated[List[CadScalar], Field(min_length=16, max_length=16)]] = Field(default=None, description="4x4 affine transform matrix as an array of 16 numbers for affine transforming entities")
    grid: Optional[CadGridParameters] = None
    __properties: ClassVar[List[str]] = ["target", "translate", "rotate", "affine", "grid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadTransformOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in target (list)
        _items = []
        if self.target:
            for _item_target in self.target:
                if _item_target:
                    _items.append(_item_target.to_dict())
            _dict['target'] = _items
        # override the default output from pydantic by calling `to_dict()` of translate
        if self.translate:
            _dict['translate'] = self.translate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rotate
        if self.rotate:
            _dict['rotate'] = self.rotate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in affine (list)
        _items = []
        if self.affine:
            for _item_affine in self.affine:
                if _item_affine:
                    _items.append(_item_affine.to_dict())
            _dict['affine'] = _items
        # override the default output from pydantic by calling `to_dict()` of grid
        if self.grid:
            _dict['grid'] = self.grid.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadTransformOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "target": [CadEntity.from_dict(_item) for _item in obj["target"]] if obj.get("target") is not None else None,
            "translate": CadTranslateParameters.from_dict(obj["translate"]) if obj.get("translate") is not None else None,
            "rotate": CadRotateParameters.from_dict(obj["rotate"]) if obj.get("rotate") is not None else None,
            "affine": [CadScalar.from_dict(_item) for _item in obj["affine"]] if obj.get("affine") is not None else None,
            "grid": CadGridParameters.from_dict(obj["grid"]) if obj.get("grid") is not None else None
        })
        return _obj


