# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.cad_box import CadBox
from allsolve_rawapi.models.cad_cone import CadCone
from allsolve_rawapi.models.cad_cylinder import CadCylinder
from allsolve_rawapi.models.cad_disk import CadDisk
from allsolve_rawapi.models.cad_line import CadLine
from allsolve_rawapi.models.cad_rectangle import CadRectangle
from allsolve_rawapi.models.cad_sphere import CadSphere
from allsolve_rawapi.models.cad_surface_rectangle import CadSurfaceRectangle
from allsolve_rawapi.models.cad_torus import CadTorus
from allsolve_rawapi.models.cad_wedge import CadWedge
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadBasicGeometry(BaseModel):
    """
    Contains a single instance of the basic geometry element. One and only one of the sphere, box, cylinder, cone, wedge, torus, disk, rectangle, line or vertex property should be set. Tag is optional but it should not overlap with other existing tags or the resulting file may miss some key details. 
    """ # noqa: E501
    sphere: Optional[CadSphere] = None
    box: Optional[CadBox] = None
    cylinder: Optional[CadCylinder] = None
    cone: Optional[CadCone] = None
    wedge: Optional[CadWedge] = None
    torus: Optional[CadTorus] = None
    disk: Optional[CadDisk] = None
    rectangle: Optional[CadRectangle] = None
    line: Optional[CadLine] = None
    surface_rectangle: Optional[CadSurfaceRectangle] = Field(default=None, alias="surfaceRectangle")
    __properties: ClassVar[List[str]] = ["sphere", "box", "cylinder", "cone", "wedge", "torus", "disk", "rectangle", "line", "surfaceRectangle"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadBasicGeometry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sphere
        if self.sphere:
            _dict['sphere'] = self.sphere.to_dict()
        # override the default output from pydantic by calling `to_dict()` of box
        if self.box:
            _dict['box'] = self.box.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cylinder
        if self.cylinder:
            _dict['cylinder'] = self.cylinder.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cone
        if self.cone:
            _dict['cone'] = self.cone.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wedge
        if self.wedge:
            _dict['wedge'] = self.wedge.to_dict()
        # override the default output from pydantic by calling `to_dict()` of torus
        if self.torus:
            _dict['torus'] = self.torus.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disk
        if self.disk:
            _dict['disk'] = self.disk.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rectangle
        if self.rectangle:
            _dict['rectangle'] = self.rectangle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of line
        if self.line:
            _dict['line'] = self.line.to_dict()
        # override the default output from pydantic by calling `to_dict()` of surface_rectangle
        if self.surface_rectangle:
            _dict['surfaceRectangle'] = self.surface_rectangle.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadBasicGeometry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sphere": CadSphere.from_dict(obj["sphere"]) if obj.get("sphere") is not None else None,
            "box": CadBox.from_dict(obj["box"]) if obj.get("box") is not None else None,
            "cylinder": CadCylinder.from_dict(obj["cylinder"]) if obj.get("cylinder") is not None else None,
            "cone": CadCone.from_dict(obj["cone"]) if obj.get("cone") is not None else None,
            "wedge": CadWedge.from_dict(obj["wedge"]) if obj.get("wedge") is not None else None,
            "torus": CadTorus.from_dict(obj["torus"]) if obj.get("torus") is not None else None,
            "disk": CadDisk.from_dict(obj["disk"]) if obj.get("disk") is not None else None,
            "rectangle": CadRectangle.from_dict(obj["rectangle"]) if obj.get("rectangle") is not None else None,
            "line": CadLine.from_dict(obj["line"]) if obj.get("line") is not None else None,
            "surfaceRectangle": CadSurfaceRectangle.from_dict(obj["surfaceRectangle"]) if obj.get("surfaceRectangle") is not None else None
        })
        return _obj


