# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.cad_distance_unit import CadDistanceUnit
from allsolve_rawapi.models.cad_unit_defaults_input import CadUnitDefaultsInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadUnitDefaults(BaseModel):
    """
    Default units for geometric operations.  _Kernel_ sets the internal CAD kernel unit. It could be useful to use micrometers or nanometers for very small geometries. The default of millimeters works well for most of the geometries, though.  _GUI_ sets the GUI model units. Setting the value to millimeters could make working with very thin entities easier.  _Mesh_ sets the unit in the FEM mesh. This affects the physics, so it is better to keep this in meters unless the unit is taken into account in the equations.  _Input_ sets the units for user-input. These units are always converted to the unit of the kernel, GUI and mesh.  If not set, the following values are used:  - kernel: millimeter  - GUI: meter  - mesh: meter  - input:     - distance: meter     - angle: degree 
    """ # noqa: E501
    kernel: Optional[CadDistanceUnit] = None
    gui: Optional[CadDistanceUnit] = None
    mesh: Optional[CadDistanceUnit] = None
    input: Optional[CadUnitDefaultsInput] = None
    __properties: ClassVar[List[str]] = ["kernel", "gui", "mesh", "input"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadUnitDefaults from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadUnitDefaults from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kernel": obj.get("kernel"),
            "gui": obj.get("gui"),
            "mesh": obj.get("mesh"),
            "input": CadUnitDefaultsInput.from_dict(obj["input"]) if obj.get("input") is not None else None
        })
        return _obj


