# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from allsolve_rawapi.models.cad_boolean_elements import CadBooleanElements
from allsolve_rawapi.models.cad_boolean_operation_type import CadBooleanOperationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadBooleanOperation(BaseModel):
    """
    Boolean operation for geometries. The type defines the type of the operation. The object is the list of cad entities the operation is performed on and the tool is the list of cad entities that forms the 'tool' for the boolean operation. For example, when drilling a hole into a box, we would use *difference* type of operation for a box *object* with a cylinder as a *tool*. 
    """ # noqa: E501
    type: CadBooleanOperationType
    object: Optional[CadBooleanElements] = None
    tool: Optional[CadBooleanElements] = None
    simplify: Optional[StrictBool] = Field(default=None, description="Simplify the result geometry by removing redundant edges and faces")
    run_parallel: Optional[StrictBool] = Field(default=True, description="Enable parallel processing for the Boolean operation to improve performance", alias="runParallel")
    use_obb: Optional[StrictBool] = Field(default=False, description="Use object oriented bounding box for intersection calculations", alias="useOBB")
    tolerance: Optional[Union[StrictFloat, StrictInt]] = Field(default=-1.0, description="Set the additional tolerance for the Boolean operation algorithm")
    glue: Optional[StrictInt] = Field(default=0, description="Set the glue option for the algorithm which allows increasing performance of the intersections of the input shapes in certain situations. Only available for fragments and fragmentall operations. 0: Glue option off 1: Glue option for shapes with partial coincidence 2: Glue option for shapes with full coincidence ")
    __properties: ClassVar[List[str]] = ["type", "object", "tool", "simplify", "runParallel", "useOBB", "tolerance", "glue"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadBooleanOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of object
        if self.object:
            _dict['object'] = self.object.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool
        if self.tool:
            _dict['tool'] = self.tool.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadBooleanOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "object": CadBooleanElements.from_dict(obj["object"]) if obj.get("object") is not None else None,
            "tool": CadBooleanElements.from_dict(obj["tool"]) if obj.get("tool") is not None else None,
            "simplify": obj.get("simplify"),
            "runParallel": obj.get("runParallel") if obj.get("runParallel") is not None else True,
            "useOBB": obj.get("useOBB") if obj.get("useOBB") is not None else False,
            "tolerance": obj.get("tolerance") if obj.get("tolerance") is not None else -1.0,
            "glue": obj.get("glue") if obj.get("glue") is not None else 0
        })
        return _obj


