# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CadAlignment(str, Enum):
    """
    Alignment of the geometry relative to the position. 
    """

    """
    allowed enum values
    """
    CENTER = 'center'
    CORNER = 'corner'
    BASE = 'base'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CadAlignment from a JSON string"""
        return cls(json.loads(json_str))


