# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_alignment import CadAlignment
from allsolve_rawapi.models.cad_angle import CadAngle
from allsolve_rawapi.models.cad_distance import CadDistance
from allsolve_rawapi.models.cad_euler_angles import CadEulerAngles
from allsolve_rawapi.models.cad_scalar import CadScalar
from allsolve_rawapi.models.cad_vector import CadVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadCylinder(BaseModel):
    """
    Cylinder geometry. Provide angle1/angle2 for partial cylinders. If no angle values are provided, a full 360 degree sweep is used. 
    """ # noqa: E501
    alignment: Optional[CadAlignment] = CadAlignment.CENTER
    position: CadVector
    axis: CadVector
    radius: CadDistance
    inner_radius: Optional[CadDistance] = Field(default=None, alias="innerRadius")
    angle1: Optional[CadAngle] = None
    angle2: Optional[CadAngle] = None
    rotation: Optional[CadEulerAngles] = None
    transform: Optional[Annotated[List[CadScalar], Field(min_length=16, max_length=16)]] = Field(default=None, description="4x4 affine transform matrix as an array of 16 numbers for affine transforming entities")
    __properties: ClassVar[List[str]] = ["alignment", "position", "axis", "radius", "innerRadius", "angle1", "angle2", "rotation", "transform"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadCylinder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        # override the default output from pydantic by calling `to_dict()` of axis
        if self.axis:
            _dict['axis'] = self.axis.to_dict()
        # override the default output from pydantic by calling `to_dict()` of radius
        if self.radius:
            _dict['radius'] = self.radius.to_dict()
        # override the default output from pydantic by calling `to_dict()` of inner_radius
        if self.inner_radius:
            _dict['innerRadius'] = self.inner_radius.to_dict()
        # override the default output from pydantic by calling `to_dict()` of angle1
        if self.angle1:
            _dict['angle1'] = self.angle1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of angle2
        if self.angle2:
            _dict['angle2'] = self.angle2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rotation
        if self.rotation:
            _dict['rotation'] = self.rotation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in transform (list)
        _items = []
        if self.transform:
            for _item_transform in self.transform:
                if _item_transform:
                    _items.append(_item_transform.to_dict())
            _dict['transform'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadCylinder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alignment": obj.get("alignment") if obj.get("alignment") is not None else CadAlignment.CENTER,
            "position": CadVector.from_dict(obj["position"]) if obj.get("position") is not None else None,
            "axis": CadVector.from_dict(obj["axis"]) if obj.get("axis") is not None else None,
            "radius": CadDistance.from_dict(obj["radius"]) if obj.get("radius") is not None else None,
            "innerRadius": CadDistance.from_dict(obj["innerRadius"]) if obj.get("innerRadius") is not None else None,
            "angle1": CadAngle.from_dict(obj["angle1"]) if obj.get("angle1") is not None else None,
            "angle2": CadAngle.from_dict(obj["angle2"]) if obj.get("angle2") is not None else None,
            "rotation": CadEulerAngles.from_dict(obj["rotation"]) if obj.get("rotation") is not None else None,
            "transform": [CadScalar.from_dict(_item) for _item in obj["transform"]] if obj.get("transform") is not None else None
        })
        return _obj


