# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.cad_basic_geometry import CadBasicGeometry
from allsolve_rawapi.models.cad_boolean import CadBoolean
from allsolve_rawapi.models.cad_boolean_operation import CadBooleanOperation
from allsolve_rawapi.models.cad_create_gds_layers_request import CadCreateGdsLayersRequest
from allsolve_rawapi.models.cad_enclosing_operation import CadEnclosingOperation
from allsolve_rawapi.models.cad_entity import CadEntity
from allsolve_rawapi.models.cad_file_definition import CadFileDefinition
from allsolve_rawapi.models.cad_metadata_operation import CadMetadataOperation
from allsolve_rawapi.models.cad_remove_entity_operation import CadRemoveEntityOperation
from allsolve_rawapi.models.cad_transform_operation import CadTransformOperation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadGeometryElement(BaseModel):
    """
    Geometry element for GeometryData. The name is optional and if not set, it is used to name the operation result objects. Disabled option can be used to skip the operation (for example in a geometric sweep). Name, parent and disabled are optional fields that do not need to be set. One, but no more, of the other fields must be set. 
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Name for the geometric element selection.")
    parent: Optional[CadEntity] = None
    cad_file: Optional[CadFileDefinition] = Field(default=None, alias="cadFile")
    geo_type: Optional[CadBasicGeometry] = Field(default=None, alias="geoType")
    boolean_operation: Optional[CadBooleanOperation] = Field(default=None, alias="booleanOperation")
    transform_operation: Optional[CadTransformOperation] = Field(default=None, alias="transformOperation")
    remove_entity_operation: Optional[CadRemoveEntityOperation] = Field(default=None, alias="removeEntityOperation")
    metadata_operation: Optional[CadMetadataOperation] = Field(default=None, alias="metadataOperation")
    enclosing_operation: Optional[CadEnclosingOperation] = Field(default=None, alias="enclosingOperation")
    gds_analysis_request: Optional[CadCreateGdsLayersRequest] = Field(default=None, alias="gdsAnalysisRequest")
    enabled: Optional[CadBoolean] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "parent", "cadFile", "geoType", "booleanOperation", "transformOperation", "removeEntityOperation", "metadataOperation", "enclosingOperation", "gdsAnalysisRequest", "enabled"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadGeometryElement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cad_file
        if self.cad_file:
            _dict['cadFile'] = self.cad_file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of geo_type
        if self.geo_type:
            _dict['geoType'] = self.geo_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of boolean_operation
        if self.boolean_operation:
            _dict['booleanOperation'] = self.boolean_operation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transform_operation
        if self.transform_operation:
            _dict['transformOperation'] = self.transform_operation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remove_entity_operation
        if self.remove_entity_operation:
            _dict['removeEntityOperation'] = self.remove_entity_operation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata_operation
        if self.metadata_operation:
            _dict['metadataOperation'] = self.metadata_operation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of enclosing_operation
        if self.enclosing_operation:
            _dict['enclosingOperation'] = self.enclosing_operation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gds_analysis_request
        if self.gds_analysis_request:
            _dict['gdsAnalysisRequest'] = self.gds_analysis_request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of enabled
        if self.enabled:
            _dict['enabled'] = self.enabled.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadGeometryElement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "parent": CadEntity.from_dict(obj["parent"]) if obj.get("parent") is not None else None,
            "cadFile": CadFileDefinition.from_dict(obj["cadFile"]) if obj.get("cadFile") is not None else None,
            "geoType": CadBasicGeometry.from_dict(obj["geoType"]) if obj.get("geoType") is not None else None,
            "booleanOperation": CadBooleanOperation.from_dict(obj["booleanOperation"]) if obj.get("booleanOperation") is not None else None,
            "transformOperation": CadTransformOperation.from_dict(obj["transformOperation"]) if obj.get("transformOperation") is not None else None,
            "removeEntityOperation": CadRemoveEntityOperation.from_dict(obj["removeEntityOperation"]) if obj.get("removeEntityOperation") is not None else None,
            "metadataOperation": CadMetadataOperation.from_dict(obj["metadataOperation"]) if obj.get("metadataOperation") is not None else None,
            "enclosingOperation": CadEnclosingOperation.from_dict(obj["enclosingOperation"]) if obj.get("enclosingOperation") is not None else None,
            "gdsAnalysisRequest": CadCreateGdsLayersRequest.from_dict(obj["gdsAnalysisRequest"]) if obj.get("gdsAnalysisRequest") is not None else None,
            "enabled": CadBoolean.from_dict(obj["enabled"]) if obj.get("enabled") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


