# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CadImportType(str, Enum):
    """
    Type of the imported CAD model file. Supported formats: - step - the standard STEP file format - iges - the standard IGES file format - gds2 - the GDSII file format with layer specifications - sat - the ACIS SAT file format - brep - the OpenCASCADE BREP file format - nas - the NASTRAN file format - msh - the Gmsh mesh file format 
    """

    """
    allowed enum values
    """
    STEP = 'step'
    IGES = 'iges'
    GDS2 = 'gds2'
    SAT = 'sat'
    BREP = 'brep'
    NAS = 'nas'
    MSH = 'msh'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CadImportType from a JSON string"""
        return cls(json.loads(json_str))


