# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.cad_entity import CadEntity
from allsolve_rawapi.models.cad_vector import CadVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadSurfaceRectangle(BaseModel):
    """
    A surface rectangle added on the plane made out of three points.  The originPoint is the origin of the relative coordinates for the surface rectangle.  The mainAxisPoint is the point defining the main axis originPoint->mainAxisPoint. This is the local x-axis (u-axis) for the surface rectangle.  The secondaryAxisPoint is a point above the main axis defining the *upward* direction. The local y-axis (v-axis) is calculated from this point, so that it is perpendicular to the local x-axis and forms such a plane with the local x-axis that the secondaryAxisPoint is on that plane, and on a positive local y-coordinate.  The originPoint, mainAxisPoint and secondaryAxisPoint must each refer to one and only one CAD vertex, must not be on the same line and they must have different coordinates.  The size parameter defines the size of the rectangle (only x and y coordinates are used, z ordinate is discarded).  The offset parameter sets the rectangle offset from the origin point (only x and y coordinates are used, z ordinate is discarded). 
    """ # noqa: E501
    origin_point: Optional[CadEntity] = Field(default=None, alias="originPoint")
    main_axis_point: Optional[CadEntity] = Field(default=None, alias="mainAxisPoint")
    secondary_axis_point: Optional[CadEntity] = Field(default=None, alias="secondaryAxisPoint")
    size: CadVector
    offset: CadVector
    __properties: ClassVar[List[str]] = ["originPoint", "mainAxisPoint", "secondaryAxisPoint", "size", "offset"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadSurfaceRectangle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of origin_point
        if self.origin_point:
            _dict['originPoint'] = self.origin_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of main_axis_point
        if self.main_axis_point:
            _dict['mainAxisPoint'] = self.main_axis_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secondary_axis_point
        if self.secondary_axis_point:
            _dict['secondaryAxisPoint'] = self.secondary_axis_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of offset
        if self.offset:
            _dict['offset'] = self.offset.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadSurfaceRectangle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "originPoint": CadEntity.from_dict(obj["originPoint"]) if obj.get("originPoint") is not None else None,
            "mainAxisPoint": CadEntity.from_dict(obj["mainAxisPoint"]) if obj.get("mainAxisPoint") is not None else None,
            "secondaryAxisPoint": CadEntity.from_dict(obj["secondaryAxisPoint"]) if obj.get("secondaryAxisPoint") is not None else None,
            "size": CadVector.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "offset": CadVector.from_dict(obj["offset"]) if obj.get("offset") is not None else None
        })
        return _obj


