# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CadSplineMethod(str, Enum):
    """
    Spline construction method for GDS edge group splinification. - polyline: Creates a simple polyline 1st order BSpline that passes through all vertices - iterative: Iteratively refines a 3rd order BSpline by sampling points 
    """

    """
    allowed enum values
    """
    POLYLINE = 'polyline'
    ITERATIVE = 'iterative'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CadSplineMethod from a JSON string"""
        return cls(json.loads(json_str))


