# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CadDistanceUnit(str, Enum):
    """
    Distance units for CAD kernel, GUI, mesh and input. Defaults:  - kernel: millimeter  - GUI: meter  - mesh: meter  - input: meter 
    """

    """
    allowed enum values
    """
    METER = 'meter'
    CENTIMETER = 'centimeter'
    MILLIMETER = 'millimeter'
    MICROMETER = 'micrometer'
    NANOMETER = 'nanometer'
    YARD = 'yard'
    FOOT = 'foot'
    INCH = 'inch'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CadDistanceUnit from a JSON string"""
        return cls(json.loads(json_str))


