# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from allsolve_rawapi.models.cad_positive_integer import CadPositiveInteger
from allsolve_rawapi.models.cad_vector import CadVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CadGridParameters(BaseModel):
    """
    Parameters for creating a grid pattern of entities
    """ # noqa: E501
    translation: CadVector
    size_x: CadPositiveInteger = Field(alias="sizeX")
    size_y: CadPositiveInteger = Field(alias="sizeY")
    size_z: CadPositiveInteger = Field(alias="sizeZ")
    __properties: ClassVar[List[str]] = ["translation", "sizeX", "sizeY", "sizeZ"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CadGridParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of translation
        if self.translation:
            _dict['translation'] = self.translation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size_x
        if self.size_x:
            _dict['sizeX'] = self.size_x.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size_y
        if self.size_y:
            _dict['sizeY'] = self.size_y.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size_z
        if self.size_z:
            _dict['sizeZ'] = self.size_z.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CadGridParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "translation": CadVector.from_dict(obj["translation"]) if obj.get("translation") is not None else None,
            "sizeX": CadPositiveInteger.from_dict(obj["sizeX"]) if obj.get("sizeX") is not None else None,
            "sizeY": CadPositiveInteger.from_dict(obj["sizeY"]) if obj.get("sizeY") is not None else None,
            "sizeZ": CadPositiveInteger.from_dict(obj["sizeZ"]) if obj.get("sizeZ") is not None else None
        })
        return _obj


