# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CustomScriptSectionName(str, Enum):
    """
    Name of the custom section to which a script will be injected to.
    """

    """
    allowed enum values
    """
    AFTERIMPORTS = 'afterImports'
    BEFOREMESHLOAD = 'beforeMeshLoad'
    AFTERMESHLOAD = 'afterMeshLoad'
    AFTERFIELDSCREATED = 'afterFieldsCreated'
    AFTERDERIVEDFIELDSCREATED = 'afterDerivedFieldsCreated'
    AFTERCONSTRAINTSCREATED = 'afterConstraintsCreated'
    AFTERPORTSCREATED = 'afterPortsCreated'
    AFTERFIELDINITS = 'afterFieldInits'
    AFTERFORMULATIONSCREATED = 'afterFormulationsCreated'
    AFTERTIMESTEPPERCREATED = 'afterTimestepperCreated'
    BEFORETRANSIENTSOLVE = 'beforeTransientSolve'
    AFTEREIGENVALUESOLVERCREATED = 'afterEigenvalueSolverCreated'
    AFTERSOLVE = 'afterSolve'
    AFTERSOLVEREAL = 'afterSolveReal'
    AFTERSOLVEIMAGINARY = 'afterSolveImaginary'
    AFTERALL = 'afterAll'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CustomScriptSectionName from a JSON string"""
        return cls(json.loads(json_str))


