# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExtrusionOverlapMode(str, Enum):
    """
    Overlap mode for the mesh extrusion: - prevent (default) - fail if there are volumes overlapping with the extruded space - remove            - remove parts of the volumes that overlap with the extruded space (not applicable for meshing_time mesh extrusion type) - extrude           - attempt to extrude the overlapping space - allow             - allow overlaps and generate pyramids in the boundary extruded and non-extruded volumes.                       *Do not use before Simcore supports pyramids.* 
    """

    """
    allowed enum values
    """
    PREVENT = 'prevent'
    REMOVE = 'remove'
    EXTRUDE = 'extrude'
    ALLOW = 'allow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExtrusionOverlapMode from a JSON string"""
        return cls(json.loads(json_str))


