# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.field_initialization_type import FieldInitializationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FieldInitialization(BaseModel):
    """
    FieldInitialization
    """ # noqa: E501
    id: StrictStr
    type: FieldInitializationType
    field_id: Optional[StrictStr] = Field(default=None, alias="fieldId")
    init_value_simulation_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="initValueSimulationId")
    init_value_output_name: StrictStr = Field(description="The name of the output in `initValueSimulationId`s output index file.", alias="initValueOutputName")
    init_value_output_specifier: Optional[StrictStr] = Field(default=None, description="The specifier of the output in `initValueSimulationId`s output index file.", alias="initValueOutputSpecifier")
    init_value_sweep_step: Optional[StrictInt] = Field(default=None, description="If specified, the initialization is taken from this sweep step of the `initValueSimulationId` output index file. The input simulation needs to be a sweep with enough steps. ", alias="initValueSweepStep")
    init_value_step: Optional[StrictStr] = Field(default=None, description="If specified, the initialization is taken from this step of the `initValueSimulationId` output index file. The input simulation needs to have a result for this step. Step in this context means the time step, eigenvalue index etc. Not sweep step. ", alias="initValueStep")
    harmonic: Optional[StrictInt] = Field(default=None, description="If specified, only this harmonic of the field is initialized using the output.")
    __properties: ClassVar[List[str]] = ["id", "type", "fieldId", "initValueSimulationId", "initValueOutputName", "initValueOutputSpecifier", "initValueSweepStep", "initValueStep", "harmonic"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FieldInitialization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FieldInitialization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "fieldId": obj.get("fieldId"),
            "initValueSimulationId": obj.get("initValueSimulationId"),
            "initValueOutputName": obj.get("initValueOutputName"),
            "initValueOutputSpecifier": obj.get("initValueOutputSpecifier"),
            "initValueSweepStep": obj.get("initValueSweepStep"),
            "initValueStep": obj.get("initValueStep"),
            "harmonic": obj.get("harmonic")
        })
        return _obj


