# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.entity_selection import EntitySelection
from allsolve_rawapi.models.expression_vector import ExpressionVector
from allsolve_rawapi.models.extrusion_layer_definition import ExtrusionLayerDefinition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FlattenAndRebuildExtrusion(BaseModel):
    """
    Extrusion by flattening the volumes on the extrusion axis and rebuilding the volumes by extruding the unique surface fragments. The volumes are flattened and split at every unique point height (relative to the extrusion direction vector). This operation will modify the mesh topology by splitting volumes, surfaces and curves and may produce a mapping file from original entities to the extruded entities. The default direction vector is along the z-axis (0, 0, 1). 
    """ # noqa: E501
    volumes: EntitySelection
    layers: List[Annotated[List[ExtrusionLayerDefinition], Field(min_length=1)]] = Field(description="Extrusion layer definitions, number of definitions must be equal to the number different point heights on the extrusion direction vector minus 1. ")
    quadrangles: StrictBool = Field(description="Generate quadrangles in the side walls of the extrusion instead of triangles.")
    direction_vector: Optional[ExpressionVector] = Field(default=None, alias="directionVector")
    __properties: ClassVar[List[str]] = ["volumes", "layers", "quadrangles", "directionVector"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlattenAndRebuildExtrusion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of volumes
        if self.volumes:
            _dict['volumes'] = self.volumes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in layers (list of list)
        _items = []
        if self.layers:
            for _item_layers in self.layers:
                if _item_layers:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item_layers if _inner_item is not None]
                    )
            _dict['layers'] = _items
        # override the default output from pydantic by calling `to_dict()` of direction_vector
        if self.direction_vector:
            _dict['directionVector'] = self.direction_vector.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlattenAndRebuildExtrusion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "volumes": EntitySelection.from_dict(obj["volumes"]) if obj.get("volumes") is not None else None,
            "layers": [
                    [ExtrusionLayerDefinition.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["layers"]
                ] if obj.get("layers") is not None else None,
            "quadrangles": obj.get("quadrangles") if obj.get("quadrangles") is not None else False,
            "directionVector": ExpressionVector.from_dict(obj["directionVector"]) if obj.get("directionVector") is not None else None
        })
        return _obj


