# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.gds_layer import GDSLayer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GDSImportConfig(BaseModel):
    """
    Parameters for importing a GDS2 file into a 3D model
    """ # noqa: E501
    layers: Annotated[List[GDSLayer], Field(min_length=1)] = Field(description="Layer definitions for the GDS2 extrusion")
    included_top_level_cells: Optional[List[StrictStr]] = Field(default=None, description="List of included top-level cell names in the GDS2 file. Leave it out or empty to include all.", alias="includedTopLevelCells")
    z_offset: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Z-coordinate field for accurate coordinates. The field can contain a raw double value with no unit (in which case the unit is considered to be millimeters) or a value with a unit suffix of either m, mm, um or nm for meters, millimeters, micrometers or nanometers, respectively. ", alias="zOffset")
    __properties: ClassVar[List[str]] = ["layers", "includedTopLevelCells", "zOffset"]

    @field_validator('z_offset')
    def z_offset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$", value):
            raise ValueError(r"must validate the regular expression /^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GDSImportConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in layers (list)
        _items = []
        if self.layers:
            for _item_layers in self.layers:
                if _item_layers:
                    _items.append(_item_layers.to_dict())
            _dict['layers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GDSImportConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "layers": [GDSLayer.from_dict(_item) for _item in obj["layers"]] if obj.get("layers") is not None else None,
            "includedTopLevelCells": obj.get("includedTopLevelCells"),
            "zOffset": obj.get("zOffset")
        })
        return _obj


