# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GDSLayer(BaseModel):
    """
    GDS2 extrusion layer description
    """ # noqa: E501
    id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Identifier for the layer")
    name: Optional[StrictStr] = Field(default=None, description="The name of the layer in the layers file")
    disabled: Optional[StrictBool] = Field(default=None, description="Toggle to disable the layer extrusion")
    previous_layer_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The optional id of the previous layer in the GDS layer stack. If left out, either the absoluteZ0 value or 0-value (GDS file z-offset) is used for z0 coordinate. ", alias="previousLayerId")
    absolute_z0: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Z-coordinate field for accurate coordinates. The field can contain a raw double value with no unit (in which case the unit is considered to be millimeters) or a value with a unit suffix of either m, mm, um or nm for meters, millimeters, micrometers or nanometers, respectively. ", alias="absoluteZ0")
    thickness: Annotated[str, Field(strict=True)] = Field(description="Z-coordinate field for accurate coordinates. The field can contain a raw double value with no unit (in which case the unit is considered to be millimeters) or a value with a unit suffix of either m, mm, um or nm for meters, millimeters, micrometers or nanometers, respectively. ")
    __properties: ClassVar[List[str]] = ["id", "name", "disabled", "previousLayerId", "absoluteZ0", "thickness"]

    @field_validator('absolute_z0')
    def absolute_z0_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$", value):
            raise ValueError(r"must validate the regular expression /^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$/")
        return value

    @field_validator('thickness')
    def thickness_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$", value):
            raise ValueError(r"must validate the regular expression /^\s*([\-]?(?:0\.|[1-9][0-9]*\.)?[0-9]+(?:[eE][+\-]?[1-9][0-9]*)?)\s*(m|mm|um|nm)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GDSLayer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GDSLayer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "disabled": obj.get("disabled"),
            "previousLayerId": obj.get("previousLayerId"),
            "absoluteZ0": obj.get("absoluteZ0"),
            "thickness": obj.get("thickness")
        })
        return _obj


