# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from allsolve_rawapi.models.python_script import PythonScript
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GeneratedSimulationScripts(BaseModel):
    """
    Response for Simulation script generation including the script content.
    """ # noqa: E501
    utils: PythonScript
    tagmappings: PythonScript
    regions: PythonScript
    expressions: PythonScript
    materials: PythonScript
    parameters: PythonScript
    simulation: PythonScript
    __properties: ClassVar[List[str]] = ["utils", "tagmappings", "regions", "expressions", "materials", "parameters", "simulation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneratedSimulationScripts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of utils
        if self.utils:
            _dict['utils'] = self.utils.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tagmappings
        if self.tagmappings:
            _dict['tagmappings'] = self.tagmappings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of regions
        if self.regions:
            _dict['regions'] = self.regions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of expressions
        if self.expressions:
            _dict['expressions'] = self.expressions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of materials
        if self.materials:
            _dict['materials'] = self.materials.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of simulation
        if self.simulation:
            _dict['simulation'] = self.simulation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneratedSimulationScripts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "utils": PythonScript.from_dict(obj["utils"]) if obj.get("utils") is not None else None,
            "tagmappings": PythonScript.from_dict(obj["tagmappings"]) if obj.get("tagmappings") is not None else None,
            "regions": PythonScript.from_dict(obj["regions"]) if obj.get("regions") is not None else None,
            "expressions": PythonScript.from_dict(obj["expressions"]) if obj.get("expressions") is not None else None,
            "materials": PythonScript.from_dict(obj["materials"]) if obj.get("materials") is not None else None,
            "parameters": PythonScript.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None,
            "simulation": PythonScript.from_dict(obj["simulation"]) if obj.get("simulation") is not None else None
        })
        return _obj


