# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GeometryPipelineVersion(str, Enum):
    """
    The version of the geometry pipeline to use. Note that the different versions are not compatible, producing different tags or other identifiers and/or support different operations. Options: v1 - use mesher-based pipeline (OpenCASCADE via Gmsh API) v2 - use geo-builder-based pipeline (direct OpenCASCADE) 
    """

    """
    allowed enum values
    """
    V1 = 'v1'
    V2 = 'v2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeometryPipelineVersion from a JSON string"""
        return cls(json.loads(json_str))


