# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GeometryFileType(str, Enum):
    """
    GeometryFileType
    """

    """
    allowed enum values
    """
    STEP = 'step'
    IGES = 'iges'
    BREP = 'brep'
    SAT = 'sat'
    MSH = 'msh'
    NAS = 'nas'
    GDS2 = 'gds2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeometryFileType from a JSON string"""
        return cls(json.loads(json_str))


