# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from allsolve_rawapi.models.job_status_type import JobStatusType
from allsolve_rawapi.models.job_type import JobType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    id: StrictStr
    parent_job_id: Optional[StrictStr] = Field(default=None, alias="parentJobId")
    type: JobType
    status: JobStatusType
    status_reason: Optional[StrictStr] = Field(default=None, alias="statusReason")
    progress: Union[StrictFloat, StrictInt]
    child_job_index: Optional[StrictInt] = Field(default=None, alias="childJobIndex")
    __properties: ClassVar[List[str]] = ["id", "parentJobId", "type", "status", "statusReason", "progress", "childJobIndex"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "parentJobId": obj.get("parentJobId"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "statusReason": obj.get("statusReason"),
            "progress": obj.get("progress"),
            "childJobIndex": obj.get("childJobIndex")
        })
        return _obj


