# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobStatusType(str, Enum):
    """
    Job statuses - submitted - The job is submitted but not yet processed for starting - starting - The job is being prepared for running - queued - The job is waiting for computation resources to become available - running - The job is running - failing - The job phase has failed and the job will end in error - error - The job is finished with an error - aborting - The user has requested the job to be aborted - aborted - The job has been aborted - processing_output - The computation is completed and output data is being processed - partial_success - At least one child job succeeded but not all - success - The job is finished successfully 
    """

    """
    allowed enum values
    """
    SUBMITTED = 'submitted'
    STARTING = 'starting'
    QUEUED = 'queued'
    RUNNING = 'running'
    FAILING = 'failing'
    ERROR = 'error'
    ABORTING = 'aborting'
    ABORTED = 'aborted'
    PROCESSING_OUTPUT = 'processing_output'
    PARTIAL_SUCCESS = 'partial_success'
    SUCCESS = 'success'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobStatusType from a JSON string"""
        return cls(json.loads(json_str))


