# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.physical_property import PhysicalProperty
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MaterialUpdate(BaseModel):
    """
    MaterialUpdate
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=100)]
    abbreviation: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=250)]] = None
    color: Annotated[str, Field(strict=True)] = Field(description="The color of the material as a RGB or RGBA hex string. both short and longhand colors work.")
    target: Optional[StrictStr] = Field(default=None, description="Id of a target Region within the project. Shared materials do not have targets.")
    orientation: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = None
    enabled: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = None
    properties: List[PhysicalProperty]
    __properties: ClassVar[List[str]] = ["name", "abbreviation", "description", "color", "target", "orientation", "enabled", "properties"]

    @field_validator('color')
    def color_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$", value):
            raise ValueError(r"must validate the regular expression /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaterialUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in properties (list)
        _items = []
        if self.properties:
            for _item_properties in self.properties:
                if _item_properties:
                    _items.append(_item_properties.to_dict())
            _dict['properties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaterialUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "abbreviation": obj.get("abbreviation"),
            "description": obj.get("description"),
            "color": obj.get("color"),
            "target": obj.get("target"),
            "orientation": obj.get("orientation"),
            "enabled": obj.get("enabled"),
            "properties": [PhysicalProperty.from_dict(_item) for _item in obj["properties"]] if obj.get("properties") is not None else None
        })
        return _obj


