# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeshExtrusionType(str, Enum):
    """
    - legacy - _*(deprecated)*_ Use the legacy mesh extrusion mode without generating tag mapping - meshing_time - _*(deprecated)*_ Use the meshing-time mesh extrusion and generate entity tag map from original geometry to the extruded geometry - collapse_and_grow - Use the collapse-and-grow mesh extrusion mode 
    """

    """
    allowed enum values
    """
    LEGACY = 'legacy'
    MESHING_TIME = 'meshing_time'
    COLLAPSE_AND_GROW = 'collapse_and_grow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeshExtrusionType from a JSON string"""
        return cls(json.loads(json_str))


