# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.job import Job
from allsolve_rawapi.models.mesh_instance_file import MeshInstanceFile
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshInstance(BaseModel):
    """
    There is one mesh instance per added override set for a mesh. In addition to this, there's always one \"default\" instance that's used when no override sets have been added. 
    """ # noqa: E501
    id: Annotated[str, Field(min_length=1, strict=True)]
    override_set: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="overrideSet")
    meshing_job: Optional[Job] = Field(default=None, alias="meshingJob")
    files: List[MeshInstanceFile]
    __properties: ClassVar[List[str]] = ["id", "overrideSet", "meshingJob", "files"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshInstance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meshing_job
        if self.meshing_job:
            _dict['meshingJob'] = self.meshing_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshInstance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "overrideSet": obj.get("overrideSet"),
            "meshingJob": Job.from_dict(obj["meshingJob"]) if obj.get("meshingJob") is not None else None,
            "files": [MeshInstanceFile.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None
        })
        return _obj


