# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.element_counts import ElementCounts
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshMetrics(BaseModel):
    """
    Metrics for FEM mesh
    """ # noqa: E501
    nodes: StrictInt = Field(description="Number of nodes in the FEM mesh.")
    elements: StrictInt = Field(description="Number of elements in the FEM mesh.")
    element_counts: Optional[List[ElementCounts]] = Field(default=None, alias="elementCounts")
    __properties: ClassVar[List[str]] = ["nodes", "elements", "elementCounts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in element_counts (list)
        _items = []
        if self.element_counts:
            for _item_element_counts in self.element_counts:
                if _item_element_counts:
                    _items.append(_item_element_counts.to_dict())
            _dict['elementCounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodes": obj.get("nodes"),
            "elements": obj.get("elements"),
            "elementCounts": [ElementCounts.from_dict(_item) for _item in obj["elementCounts"]] if obj.get("elementCounts") is not None else None
        })
        return _obj


