# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeshAlgorithm(str, Enum):
    """
    The mesh algorithm to use for FEM meshing - gmsh         - plain Gmsh - mesh-refiner - octree-based automatic mesh refiner 
    """

    """
    allowed enum values
    """
    GMSH = 'gmsh'
    MESH_MINUS_REFINER = 'mesh-refiner'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeshAlgorithm from a JSON string"""
        return cls(json.loads(json_str))


