# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.job_status_type import JobStatusType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshFile(BaseModel):
    """
    An actual physical file produced by meshing.
    """ # noqa: E501
    id: StrictStr
    last_unlinked_at: Optional[datetime] = Field(default=None, description="When was the file last unlinked from a mesh instance. This can be used to figure out if we should delete the file This is simply the last time the file was unlinked from any mesh instance. The file might still be linked to other instances. To know if the file is fully orphaned, you also need to check that no instance references it. ", alias="lastUnlinkedAt")
    input_hash: StrictStr = Field(alias="inputHash")
    job_id: Optional[StrictStr] = Field(default=None, alias="jobId")
    job_status: Optional[JobStatusType] = Field(default=None, alias="jobStatus")
    legacy_file_prefix: Optional[StrictStr] = Field(default=None, description="The old S3 prefix for this file. This is used to find the file for the legacy mesh files. This should never be set for any new files. ", alias="legacyFilePrefix")
    __properties: ClassVar[List[str]] = ["id", "lastUnlinkedAt", "inputHash", "jobId", "jobStatus", "legacyFilePrefix"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "lastUnlinkedAt": obj.get("lastUnlinkedAt"),
            "inputHash": obj.get("inputHash"),
            "jobId": obj.get("jobId"),
            "jobStatus": obj.get("jobStatus"),
            "legacyFilePrefix": obj.get("legacyFilePrefix")
        })
        return _obj


