# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeshDensity(str, Enum):
    """
    Project mesh density
    """

    """
    allowed enum values
    """
    USERDEFINED = 'userDefined'
    COARSE = 'coarse'
    DEFAULT = 'default'
    FINE = 'fine'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeshDensity from a JSON string"""
        return cls(json.loads(json_str))


