# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.mesh_density import MeshDensity
from allsolve_rawapi.models.mesh_parameters import MeshParameters
from allsolve_rawapi.models.mesh_support_data import MeshSupportData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshUpdate(BaseModel):
    """
    MeshUpdate
    """ # noqa: E501
    name: StrictStr
    density: Optional[MeshDensity] = None
    quality: Optional[MeshDensity] = None
    max_run_time_minutes: StrictInt = Field(description="Maximum runtime for the meshing job.", alias="maxRunTimeMinutes")
    node_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="nodeType")
    parameters: MeshParameters
    support_data: MeshSupportData = Field(alias="supportData")
    override_sets: List[Annotated[str, Field(min_length=1, strict=True)]] = Field(alias="overrideSets")
    __properties: ClassVar[List[str]] = ["name", "density", "quality", "maxRunTimeMinutes", "nodeType", "parameters", "supportData", "overrideSets"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of support_data
        if self.support_data:
            _dict['supportData'] = self.support_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "density": obj.get("density"),
            "quality": obj.get("quality"),
            "maxRunTimeMinutes": obj.get("maxRunTimeMinutes"),
            "nodeType": obj.get("nodeType"),
            "parameters": MeshParameters.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None,
            "supportData": MeshSupportData.from_dict(obj["supportData"]) if obj.get("supportData") is not None else None,
            "overrideSets": obj.get("overrideSets")
        })
        return _obj


