# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.auto_transfinite_entry import AutoTransfiniteEntry
from allsolve_rawapi.models.mesh_algorithm import MeshAlgorithm
from allsolve_rawapi.models.mesh_extrusion import MeshExtrusion
from allsolve_rawapi.models.selective_mesh_refinement import SelectiveMeshRefinement
from allsolve_rawapi.models.structured_mesh_definitions import StructuredMeshDefinitions
from allsolve_rawapi.models.structured_meshing import StructuredMeshing
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshParameters(BaseModel):
    """
    Mesh parameters
    """ # noqa: E501
    mesh_algorithm: Optional[MeshAlgorithm] = Field(default=None, alias="meshAlgorithm")
    min_size_factor: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="minSizeFactor")
    max_size_factor: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="maxSizeFactor")
    scale_factor: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="scaleFactor")
    curvature_enhancement: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="curvatureEnhancement")
    mesh_size_min: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="meshSizeMin")
    mesh_size_max: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="meshSizeMax")
    curved_mesh: Optional[StrictBool] = Field(default=None, description="Use curved mesh (2nd order)", alias="curvedMesh")
    target_width_to_height_ratio: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="targetWidthToHeightRatio")
    selective_refinement: Optional[SelectiveMeshRefinement] = Field(default=None, alias="selectiveRefinement")
    structured_meshing: Optional[StructuredMeshing] = Field(default=None, alias="structuredMeshing")
    structured_mesh_definitions: Optional[StructuredMeshDefinitions] = Field(default=None, alias="structuredMeshDefinitions")
    mesh_extrusion: Optional[MeshExtrusion] = Field(default=None, alias="meshExtrusion")
    auto_transfinite_meshing: Optional[List[AutoTransfiniteEntry]] = Field(default=None, description="Automatic transfinite meshing configuration. An array of entries, each pairing anisotropic element sizes with target entity selections. ", alias="autoTransfiniteMeshing")
    __properties: ClassVar[List[str]] = ["meshAlgorithm", "minSizeFactor", "maxSizeFactor", "scaleFactor", "curvatureEnhancement", "meshSizeMin", "meshSizeMax", "curvedMesh", "targetWidthToHeightRatio", "selectiveRefinement", "structuredMeshing", "structuredMeshDefinitions", "meshExtrusion", "autoTransfiniteMeshing"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of selective_refinement
        if self.selective_refinement:
            _dict['selectiveRefinement'] = self.selective_refinement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of structured_meshing
        if self.structured_meshing:
            _dict['structuredMeshing'] = self.structured_meshing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of structured_mesh_definitions
        if self.structured_mesh_definitions:
            _dict['structuredMeshDefinitions'] = self.structured_mesh_definitions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mesh_extrusion
        if self.mesh_extrusion:
            _dict['meshExtrusion'] = self.mesh_extrusion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in auto_transfinite_meshing (list)
        _items = []
        if self.auto_transfinite_meshing:
            for _item_auto_transfinite_meshing in self.auto_transfinite_meshing:
                if _item_auto_transfinite_meshing:
                    _items.append(_item_auto_transfinite_meshing.to_dict())
            _dict['autoTransfiniteMeshing'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meshAlgorithm": obj.get("meshAlgorithm"),
            "minSizeFactor": obj.get("minSizeFactor"),
            "maxSizeFactor": obj.get("maxSizeFactor"),
            "scaleFactor": obj.get("scaleFactor"),
            "curvatureEnhancement": obj.get("curvatureEnhancement"),
            "meshSizeMin": obj.get("meshSizeMin"),
            "meshSizeMax": obj.get("meshSizeMax"),
            "curvedMesh": obj.get("curvedMesh"),
            "targetWidthToHeightRatio": obj.get("targetWidthToHeightRatio"),
            "selectiveRefinement": SelectiveMeshRefinement.from_dict(obj["selectiveRefinement"]) if obj.get("selectiveRefinement") is not None else None,
            "structuredMeshing": StructuredMeshing.from_dict(obj["structuredMeshing"]) if obj.get("structuredMeshing") is not None else None,
            "structuredMeshDefinitions": StructuredMeshDefinitions.from_dict(obj["structuredMeshDefinitions"]) if obj.get("structuredMeshDefinitions") is not None else None,
            "meshExtrusion": MeshExtrusion.from_dict(obj["meshExtrusion"]) if obj.get("meshExtrusion") is not None else None,
            "autoTransfiniteMeshing": [AutoTransfiniteEntry.from_dict(_item) for _item in obj["autoTransfiniteMeshing"]] if obj.get("autoTransfiniteMeshing") is not None else None
        })
        return _obj


