# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from allsolve_rawapi.models.meshing_error_code import MeshingErrorCode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshingError(BaseModel):
    """
    Meshing error
    """ # noqa: E501
    error_code: MeshingErrorCode = Field(alias="errorCode")
    description: Optional[StrictStr] = Field(default=None, description="Error description")
    volumes: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="List of entity tags that create a region.")
    surfaces: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="List of entity tags that create a region.")
    curves: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="List of entity tags that create a region.")
    points: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="List of entity tags that create a region.")
    numeric_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Numeric value related to the error", alias="numericValue")
    __properties: ClassVar[List[str]] = ["errorCode", "description", "volumes", "surfaces", "curves", "points", "numericValue"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshingError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshingError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "errorCode": obj.get("errorCode"),
            "description": obj.get("description"),
            "volumes": obj.get("volumes"),
            "surfaces": obj.get("surfaces"),
            "curves": obj.get("curves"),
            "points": obj.get("points"),
            "numericValue": obj.get("numericValue")
        })
        return _obj


