# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.extrusion_overlap_mode import ExtrusionOverlapMode
from allsolve_rawapi.models.mesh_extrusion_type import MeshExtrusionType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeshExtrusion(BaseModel):
    """
    Mesh extrusion configuration for a prism-mesh extruded from 2D elements along the Z-axis.
    """ # noqa: E501
    extrusion_overlap_mode: ExtrusionOverlapMode = Field(alias="extrusionOverlapMode")
    volume_ids: Optional[Annotated[List[Annotated[int, Field(strict=True, ge=0)]], Field(min_length=0)]] = Field(default=None, description="Geometry tag list containing at least one tag. Note: an empty array is allowed for the construction phase of the geometries but must not be sent to the geometry generation functionality. ", alias="volumeIds")
    volume_regions: Optional[List[StrictStr]] = Field(default=None, description="Regions for which the extrusion applies to. Either this or `volumeIds` must be provided but not both. ", alias="volumeRegions")
    sublayers: List[Annotated[str, Field(strict=True, max_length=5000)]]
    type: Optional[MeshExtrusionType] = None
    __properties: ClassVar[List[str]] = ["extrusionOverlapMode", "volumeIds", "volumeRegions", "sublayers", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeshExtrusion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeshExtrusion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "extrusionOverlapMode": obj.get("extrusionOverlapMode"),
            "volumeIds": obj.get("volumeIds"),
            "volumeRegions": obj.get("volumeRegions"),
            "sublayers": obj.get("sublayers"),
            "type": obj.get("type")
        })
        return _obj


