# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeshingErrorCode(str, Enum):
    """
    Meshing error codes: - internal_error                         - internal meshing error - extrusion_overlapping_volumes          - extruded meshing has overlapping volumes in `prevent` extrusion overlap mode - extrusion_invalid_overlap_mode         - invalid extrusion overlap mode selected - extrusion_invalid_number_of_sublayers  - invalid number of sublayers for extrusion. The numericValue field contains the required amount. - extrusion_invalid_settings             - invalid settings for extruded meshing - extrusion_overlapping_extrusion_layers - extrusion layers overlap - generic_error                          - generic meshing error 
    """

    """
    allowed enum values
    """
    INTERNAL_ERROR = 'internal_error'
    EXTRUSION_OVERLAPPING_VOLUMES = 'extrusion_overlapping_volumes'
    EXTRUSION_INVALID_OVERLAP_MODE = 'extrusion_invalid_overlap_mode'
    EXTRUSION_INVALID_NUMBER_OF_SUBLAYERS = 'extrusion_invalid_number_of_sublayers'
    EXTRUSION_INVALID_SETTINGS = 'extrusion_invalid_settings'
    EXTRUSION_OVERLAPPING_EXTRUSION_LAYERS = 'extrusion_overlapping_extrusion_layers'
    GENERIC_ERROR = 'generic_error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeshingErrorCode from a JSON string"""
        return cls(json.loads(json_str))


