# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrganizationQuota(BaseModel):
    """
    OrganizationQuota
    """ # noqa: E501
    total_credits: StrictInt = Field(description="How many credits are available for usage. ", alias="totalCredits")
    used_credits: Union[StrictFloat, StrictInt] = Field(description="How many credits have been used. ", alias="usedCredits")
    total_running_cores: StrictInt = Field(alias="totalRunningCores")
    total_reserved_cores: StrictInt = Field(alias="totalReservedCores")
    max_concurrent_cores: StrictInt = Field(alias="maxConcurrentCores")
    __properties: ClassVar[List[str]] = ["totalCredits", "usedCredits", "totalRunningCores", "totalReservedCores", "maxConcurrentCores"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationQuota from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationQuota from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalCredits": obj.get("totalCredits"),
            "usedCredits": obj.get("usedCredits"),
            "totalRunningCores": obj.get("totalRunningCores"),
            "totalReservedCores": obj.get("totalReservedCores"),
            "maxConcurrentCores": obj.get("maxConcurrentCores")
        })
        return _obj


