# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.physical_property_alternative_definition import PhysicalPropertyAlternativeDefinition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PhysicalPropertyDefinition(BaseModel):
    """
    PhysicalPropertyDefinition
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    symbol: StrictStr
    unit: Optional[StrictStr] = None
    source_only: StrictBool = Field(description="If true, the property is only a source property and can never be defined independently.", alias="sourceOnly")
    alternatives: List[PhysicalPropertyAlternativeDefinition] = Field(description="Alternatives contains all possible ways to define the physical property. For example, if a property can be an isotropic scalar value or an anisotropic 3x3 matrix value, there will be two alternatives. If the property can be defined in terms of other properties, there will be one alternative for each way to define it. For example the elasticity matrix could be defined in terms of the poissons ratio and youngs modulus, in terms of bulk modulus and shear modulus or by providing the whole 6x6 matrix. ")
    __properties: ClassVar[List[str]] = ["id", "name", "symbol", "unit", "sourceOnly", "alternatives"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PhysicalPropertyDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in alternatives (list)
        _items = []
        if self.alternatives:
            for _item_alternatives in self.alternatives:
                if _item_alternatives:
                    _items.append(_item_alternatives.to_dict())
            _dict['alternatives'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PhysicalPropertyDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "symbol": obj.get("symbol"),
            "unit": obj.get("unit"),
            "sourceOnly": obj.get("sourceOnly"),
            "alternatives": [PhysicalPropertyAlternativeDefinition.from_dict(_item) for _item in obj["alternatives"]] if obj.get("alternatives") is not None else None
        })
        return _obj


