# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from allsolve_rawapi.models.model_field import ModelField
from allsolve_rawapi.models.physics import Physics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PhysicsCreationResponse(BaseModel):
    """
    PhysicsCreationResponse
    """ # noqa: E501
    physics: Physics
    new_fields: List[ModelField] = Field(alias="newFields")
    __properties: ClassVar[List[str]] = ["physics", "newFields"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PhysicsCreationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of physics
        if self.physics:
            _dict['physics'] = self.physics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in new_fields (list)
        _items = []
        if self.new_fields:
            for _item_new_fields in self.new_fields:
                if _item_new_fields:
                    _items.append(_item_new_fields.to_dict())
            _dict['newFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PhysicsCreationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "physics": Physics.from_dict(obj["physics"]) if obj.get("physics") is not None else None,
            "newFields": [ModelField.from_dict(_item) for _item in obj["newFields"]] if obj.get("newFields") is not None else None
        })
        return _obj


