# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.geometry_pipeline_version import GeometryPipelineVersion
from allsolve_rawapi.models.pml_settings import PMLSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Project(BaseModel):
    """
    Project
    """ # noqa: E501
    id: Annotated[str, Field(min_length=1, strict=True)]
    name: Annotated[str, Field(min_length=1, strict=True)]
    description: StrictStr
    readonly: StrictBool
    labels: List[StrictStr]
    geometry_pipeline_version: Optional[GeometryPipelineVersion] = Field(default=None, alias="geometryPipelineVersion")
    dimension: Optional[Annotated[int, Field(le=3, strict=True, ge=1)]] = None
    geometry_no_implicit_fragment: Optional[StrictBool] = Field(default=None, alias="geometryNoImplicitFragment")
    pml_settings: Optional[PMLSettings] = Field(default=None, alias="pmlSettings")
    copy_files_job_id: Optional[StrictStr] = Field(default=None, description="This is non-null if this project is a copy of another project and the files are still being copied. This project is not functional before this job succeeds. ", alias="copyFilesJobId")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "readonly", "labels", "geometryPipelineVersion", "dimension", "geometryNoImplicitFragment", "pmlSettings", "copyFilesJobId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Project from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pml_settings
        if self.pml_settings:
            _dict['pmlSettings'] = self.pml_settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Project from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "readonly": obj.get("readonly"),
            "labels": obj.get("labels"),
            "geometryPipelineVersion": obj.get("geometryPipelineVersion"),
            "dimension": obj.get("dimension"),
            "geometryNoImplicitFragment": obj.get("geometryNoImplicitFragment"),
            "pmlSettings": PMLSettings.from_dict(obj["pmlSettings"]) if obj.get("pmlSettings") is not None else None,
            "copyFilesJobId": obj.get("copyFilesJobId")
        })
        return _obj


