# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProjectTypeFilter(str, Enum):
    """
    Filter by project creation type. API returns only projects created via the public API, NORMAL returns only projects not created via the public API, ALL returns all projects.
    """

    """
    allowed enum values
    """
    API = 'API'
    NORMAL = 'NORMAL'
    ALL = 'ALL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProjectTypeFilter from a JSON string"""
        return cls(json.loads(json_str))


