# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.python_script_custom_section import PythonScriptCustomSection
from allsolve_rawapi.models.python_script_import import PythonScriptImport
from allsolve_rawapi.models.python_script_section import PythonScriptSection
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PythonScript(BaseModel):
    """
    PythonScript
    """ # noqa: E501
    module: StrictStr
    code: StrictStr
    imports: List[PythonScriptImport]
    custom_sections: Optional[List[PythonScriptCustomSection]] = Field(default=None, alias="customSections")
    sections: Optional[List[PythonScriptSection]] = None
    __properties: ClassVar[List[str]] = ["module", "code", "imports", "customSections", "sections"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PythonScript from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in imports (list)
        _items = []
        if self.imports:
            for _item_imports in self.imports:
                if _item_imports:
                    _items.append(_item_imports.to_dict())
            _dict['imports'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_sections (list)
        _items = []
        if self.custom_sections:
            for _item_custom_sections in self.custom_sections:
                if _item_custom_sections:
                    _items.append(_item_custom_sections.to_dict())
            _dict['customSections'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item_sections in self.sections:
                if _item_sections:
                    _items.append(_item_sections.to_dict())
            _dict['sections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PythonScript from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "module": obj.get("module"),
            "code": obj.get("code"),
            "imports": [PythonScriptImport.from_dict(_item) for _item in obj["imports"]] if obj.get("imports") is not None else None,
            "customSections": [PythonScriptCustomSection.from_dict(_item) for _item in obj["customSections"]] if obj.get("customSections") is not None else None,
            "sections": [PythonScriptSection.from_dict(_item) for _item in obj["sections"]] if obj.get("sections") is not None else None
        })
        return _obj


