# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RegionRuleOperation(str, Enum):
    """
    RegionRuleOperation
    """

    """
    allowed enum values
    """
    UNION = 'union'
    INTERSECTION = 'intersection'
    DIFFERENCE = 'difference'
    SYMMETRIC_DIFFERENCE = 'symmetric_difference'
    COMPLEMENT = 'complement'
    BOUNDARY = 'boundary'
    SELECTOR = 'selector'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RegionRuleOperation from a JSON string"""
        return cls(json.loads(json_str))


