# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.entity_type import EntityType
from allsolve_rawapi.models.region_rule import RegionRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Region(BaseModel):
    """
    Region
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    shared: StrictBool
    entity_tags: List[Annotated[int, Field(strict=True, ge=0)]] = Field(description="List of entity tags that create a region.", alias="entityTags")
    entity_type: EntityType = Field(alias="entityType")
    physical_region: StrictInt = Field(alias="physicalRegion")
    region_rule: Optional[RegionRule] = Field(default=None, alias="regionRule")
    __properties: ClassVar[List[str]] = ["id", "name", "shared", "entityTags", "entityType", "physicalRegion", "regionRule"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Region from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of region_rule
        if self.region_rule:
            _dict['regionRule'] = self.region_rule.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Region from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "shared": obj.get("shared") if obj.get("shared") is not None else True,
            "entityTags": obj.get("entityTags"),
            "entityType": obj.get("entityType"),
            "physicalRegion": obj.get("physicalRegion"),
            "regionRule": RegionRule.from_dict(obj["regionRule"]) if obj.get("regionRule") is not None else None
        })
        return _obj


