# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.attribute_path import AttributePath
from allsolve_rawapi.models.expression_bounding_box import ExpressionBoundingBox
from allsolve_rawapi.models.expression_vector import ExpressionVector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RegionSelector(BaseModel):
    """
    RegionSelector
    """ # noqa: E501
    bounding_box: Optional[ExpressionBoundingBox] = Field(default=None, alias="boundingBox")
    min_size: Optional[ExpressionVector] = Field(default=None, alias="minSize")
    max_size: Optional[ExpressionVector] = Field(default=None, alias="maxSize")
    attribute_path: Optional[AttributePath] = Field(default=None, alias="attributePath")
    __properties: ClassVar[List[str]] = ["boundingBox", "minSize", "maxSize", "attributePath"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegionSelector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bounding_box
        if self.bounding_box:
            _dict['boundingBox'] = self.bounding_box.to_dict()
        # override the default output from pydantic by calling `to_dict()` of min_size
        if self.min_size:
            _dict['minSize'] = self.min_size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of max_size
        if self.max_size:
            _dict['maxSize'] = self.max_size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attribute_path
        if self.attribute_path:
            _dict['attributePath'] = self.attribute_path.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegionSelector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "boundingBox": ExpressionBoundingBox.from_dict(obj["boundingBox"]) if obj.get("boundingBox") is not None else None,
            "minSize": ExpressionVector.from_dict(obj["minSize"]) if obj.get("minSize") is not None else None,
            "maxSize": ExpressionVector.from_dict(obj["maxSize"]) if obj.get("maxSize") is not None else None,
            "attributePath": AttributePath.from_dict(obj["attributePath"]) if obj.get("attributePath") is not None else None
        })
        return _obj


