# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReservationStatus(str, Enum):
    """
    The status of the resource reservation
    """

    """
    allowed enum values
    """
    QUEUED = 'queued'
    RESERVING = 'reserving'
    RESERVED = 'reserved'
    RELEASING = 'releasing'
    RELEASED = 'released'
    FAILING = 'failing'
    FAILED = 'failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReservationStatus from a JSON string"""
        return cls(json.loads(json_str))


