# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourceReservationRequest(BaseModel):
    """
    ResourceReservationRequest
    """ # noqa: E501
    node_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="nodeType")
    main_node_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="mainNodeType")
    num_nodes: Annotated[int, Field(strict=True, ge=1)] = Field(description="The number of nodes to reserve.", alias="numNodes")
    num_replicas: Annotated[int, Field(strict=True, ge=1)] = Field(description="How many replicas of the whole reservation should be reserved. For example if you're reserving 10 nodes and you set `numReplicas` to 3 then 30 nodes will get reserved. If a main node instance type is defined there will be 3 main node instances and 27 worker instances. ", alias="numReplicas")
    team_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="teamId")
    __properties: ClassVar[List[str]] = ["nodeType", "mainNodeType", "numNodes", "numReplicas", "teamId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceReservationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceReservationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeType": obj.get("nodeType"),
            "mainNodeType": obj.get("mainNodeType"),
            "numNodes": obj.get("numNodes"),
            "numReplicas": obj.get("numReplicas"),
            "teamId": obj.get("teamId")
        })
        return _obj


