# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.selective_mesh_refinement_item import SelectiveMeshRefinementItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SelectiveMeshRefinement(BaseModel):
    """
    Selective mesh refinement configuration for the model
    """ # noqa: E501
    volumes: Optional[Annotated[List[SelectiveMeshRefinementItem], Field(min_length=1)]] = Field(default=None, description="List of selective mesh refinement properties")
    surfaces: Optional[Annotated[List[SelectiveMeshRefinementItem], Field(min_length=1)]] = Field(default=None, description="List of selective mesh refinement properties")
    curves: Optional[Annotated[List[SelectiveMeshRefinementItem], Field(min_length=1)]] = Field(default=None, description="List of selective mesh refinement properties")
    __properties: ClassVar[List[str]] = ["volumes", "surfaces", "curves"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SelectiveMeshRefinement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict['volumes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in surfaces (list)
        _items = []
        if self.surfaces:
            for _item_surfaces in self.surfaces:
                if _item_surfaces:
                    _items.append(_item_surfaces.to_dict())
            _dict['surfaces'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in curves (list)
        _items = []
        if self.curves:
            for _item_curves in self.curves:
                if _item_curves:
                    _items.append(_item_curves.to_dict())
            _dict['curves'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SelectiveMeshRefinement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "volumes": [SelectiveMeshRefinementItem.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None,
            "surfaces": [SelectiveMeshRefinementItem.from_dict(_item) for _item in obj["surfaces"]] if obj.get("surfaces") is not None else None,
            "curves": [SelectiveMeshRefinementItem.from_dict(_item) for _item in obj["curves"]] if obj.get("curves") is not None else None
        })
        return _obj


