# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from allsolve_rawapi.models.shared_expression_arg import SharedExpressionArg
from allsolve_rawapi.models.shared_expression_owner_type import SharedExpressionOwnerType
from allsolve_rawapi.models.shared_expression_type import SharedExpressionType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SharedExpression(BaseModel):
    """
    SharedExpression
    """ # noqa: E501
    id: StrictStr
    name: Annotated[str, Field(strict=True)]
    type: SharedExpressionType
    description: Annotated[str, Field(strict=True, max_length=4096)]
    owner: SharedExpressionOwnerType
    origin: Optional[StrictStr] = Field(default=None, description="Id of the original shared expression if this is a copy.")
    args: Optional[List[SharedExpressionArg]] = None
    expression: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = None
    values: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(max_length=1000000)]] = None
    cubic_interpolation: Optional[StrictBool] = Field(default=None, description="If the expression is of type `interpolatedFunction` this flag indicates whether the values should be interpolated linearly or using a natural cubic spline. ", alias="cubicInterpolation")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    last_modified_at: Optional[datetime] = Field(default=None, alias="lastModifiedAt")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "description", "owner", "origin", "args", "expression", "values", "cubicInterpolation", "createdAt", "lastModifiedAt", "lastModifiedBy"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]{0,254}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z_][a-zA-Z0-9_]{0,254}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedExpression from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in args (list)
        _items = []
        if self.args:
            for _item_args in self.args:
                if _item_args:
                    _items.append(_item_args.to_dict())
            _dict['args'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedExpression from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "description": obj.get("description"),
            "owner": obj.get("owner"),
            "origin": obj.get("origin"),
            "args": [SharedExpressionArg.from_dict(_item) for _item in obj["args"]] if obj.get("args") is not None else None,
            "expression": obj.get("expression"),
            "values": obj.get("values"),
            "cubicInterpolation": obj.get("cubicInterpolation"),
            "createdAt": obj.get("createdAt"),
            "lastModifiedAt": obj.get("lastModifiedAt"),
            "lastModifiedBy": obj.get("lastModifiedBy")
        })
        return _obj


