# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.analysis_type import AnalysisType
from allsolve_rawapi.models.disabled_script_section import DisabledScriptSection
from allsolve_rawapi.models.distributed_solver_mode import DistributedSolverMode
from allsolve_rawapi.models.field_initialization import FieldInitialization
from allsolve_rawapi.models.interaction import Interaction
from allsolve_rawapi.models.job import Job
from allsolve_rawapi.models.simulation_input_file import SimulationInputFile
from allsolve_rawapi.models.simulation_script import SimulationScript
from allsolve_rawapi.models.solver_precision import SolverPrecision
from allsolve_rawapi.models.timestep_algorithm import TimestepAlgorithm
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Simulation(BaseModel):
    """
    Simulation
    """ # noqa: E501
    id: Annotated[str, Field(min_length=1, strict=True)]
    name: StrictStr
    description: Optional[StrictStr] = None
    scripts: List[SimulationScript] = Field(description="List of simulation scripts. Empty when scripts are not defined.")
    analysis_type: Optional[AnalysisType] = Field(default=None, alias="analysisType")
    harmonics: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="List of harmonics")
    simulation_job: Optional[Job] = Field(default=None, alias="simulationJob")
    mesh: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    node_count: Optional[Annotated[int, Field(le=10000, strict=True, ge=1)]] = Field(default=None, alias="nodeCount")
    node_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="nodeType")
    main_node_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="mainNodeType")
    start_time: Optional[datetime] = Field(default=None, alias="startTime")
    max_run_time_minutes: StrictInt = Field(alias="maxRunTimeMinutes")
    output_interactions: Optional[List[Interaction]] = Field(default=None, alias="outputInteractions")
    override_set: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="overrideSet")
    input_files: List[SimulationInputFile] = Field(alias="inputFiles")
    solver_mode: DistributedSolverMode = Field(alias="solverMode")
    solver_precision: Optional[SolverPrecision] = Field(default=None, alias="solverPrecision")
    disabled_script_sections: Optional[List[DisabledScriptSection]] = Field(default=None, description="A list of section names that should be disabled in the generated scripts.", alias="disabledScriptSections")
    physics: Optional[List[StrictStr]] = Field(default=None, description="A list of physics ids to simulate. This selection is only needed for some analysis types like `transient`. By default all physics are simulated.")
    internal_start_time: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="internalStartTime")
    internal_end_time: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="internalEndTime")
    internal_timestep_size: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="internalTimestepSize")
    timestep_algorithm: Optional[TimestepAlgorithm] = Field(default=None, alias="timestepAlgorithm")
    fundamental_frequency: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="fundamentalFrequency")
    num_fft_samples: Optional[StrictInt] = Field(default=None, alias="numFFTSamples")
    num_requested_eigenmodes: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="numRequestedEigenmodes")
    target_eigenfrequency: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="targetEigenfrequency")
    eigenmode_port_analysis: Optional[StrictBool] = Field(default=None, description="If the enabled physics contain any eigenmode ports and this is true the simulation will run an eigenmode analysis instead of normal simulation. If there are no eigenmode ports, this boolean has no effect. ", alias="eigenmodePortAnalysis")
    solver_tolerance: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="solverTolerance")
    nonlinear_solver_tolerance: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="nonlinearSolverTolerance")
    nonlinear_solver_max_iterations: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="nonlinearSolverMaxIterations")
    eigenmode_solver_tolerance: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="eigenmodeSolverTolerance")
    eigenmode_solver_max_iterations: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="eigenmodeSolverMaxIterations")
    target_frequency: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="targetFrequency")
    numerical_jacobian: Optional[StrictBool] = Field(default=None, alias="numericalJacobian")
    field_initializations: Optional[List[FieldInitialization]] = Field(default=None, alias="fieldInitializations")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "scripts", "analysisType", "harmonics", "simulationJob", "mesh", "nodeCount", "nodeType", "mainNodeType", "startTime", "maxRunTimeMinutes", "outputInteractions", "overrideSet", "inputFiles", "solverMode", "solverPrecision", "disabledScriptSections", "physics", "internalStartTime", "internalEndTime", "internalTimestepSize", "timestepAlgorithm", "fundamentalFrequency", "numFFTSamples", "numRequestedEigenmodes", "targetEigenfrequency", "eigenmodePortAnalysis", "solverTolerance", "nonlinearSolverTolerance", "nonlinearSolverMaxIterations", "eigenmodeSolverTolerance", "eigenmodeSolverMaxIterations", "targetFrequency", "numericalJacobian", "fieldInitializations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Simulation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scripts (list)
        _items = []
        if self.scripts:
            for _item_scripts in self.scripts:
                if _item_scripts:
                    _items.append(_item_scripts.to_dict())
            _dict['scripts'] = _items
        # override the default output from pydantic by calling `to_dict()` of simulation_job
        if self.simulation_job:
            _dict['simulationJob'] = self.simulation_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in output_interactions (list)
        _items = []
        if self.output_interactions:
            for _item_output_interactions in self.output_interactions:
                if _item_output_interactions:
                    _items.append(_item_output_interactions.to_dict())
            _dict['outputInteractions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in input_files (list)
        _items = []
        if self.input_files:
            for _item_input_files in self.input_files:
                if _item_input_files:
                    _items.append(_item_input_files.to_dict())
            _dict['inputFiles'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in field_initializations (list)
        _items = []
        if self.field_initializations:
            for _item_field_initializations in self.field_initializations:
                if _item_field_initializations:
                    _items.append(_item_field_initializations.to_dict())
            _dict['fieldInitializations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Simulation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "scripts": [SimulationScript.from_dict(_item) for _item in obj["scripts"]] if obj.get("scripts") is not None else None,
            "analysisType": obj.get("analysisType"),
            "harmonics": obj.get("harmonics"),
            "simulationJob": Job.from_dict(obj["simulationJob"]) if obj.get("simulationJob") is not None else None,
            "mesh": obj.get("mesh"),
            "nodeCount": obj.get("nodeCount"),
            "nodeType": obj.get("nodeType"),
            "mainNodeType": obj.get("mainNodeType"),
            "startTime": obj.get("startTime"),
            "maxRunTimeMinutes": obj.get("maxRunTimeMinutes"),
            "outputInteractions": [Interaction.from_dict(_item) for _item in obj["outputInteractions"]] if obj.get("outputInteractions") is not None else None,
            "overrideSet": obj.get("overrideSet"),
            "inputFiles": [SimulationInputFile.from_dict(_item) for _item in obj["inputFiles"]] if obj.get("inputFiles") is not None else None,
            "solverMode": obj.get("solverMode"),
            "solverPrecision": obj.get("solverPrecision"),
            "disabledScriptSections": obj.get("disabledScriptSections"),
            "physics": obj.get("physics"),
            "internalStartTime": obj.get("internalStartTime"),
            "internalEndTime": obj.get("internalEndTime"),
            "internalTimestepSize": obj.get("internalTimestepSize"),
            "timestepAlgorithm": obj.get("timestepAlgorithm"),
            "fundamentalFrequency": obj.get("fundamentalFrequency"),
            "numFFTSamples": obj.get("numFFTSamples"),
            "numRequestedEigenmodes": obj.get("numRequestedEigenmodes"),
            "targetEigenfrequency": obj.get("targetEigenfrequency"),
            "eigenmodePortAnalysis": obj.get("eigenmodePortAnalysis"),
            "solverTolerance": obj.get("solverTolerance"),
            "nonlinearSolverTolerance": obj.get("nonlinearSolverTolerance"),
            "nonlinearSolverMaxIterations": obj.get("nonlinearSolverMaxIterations"),
            "eigenmodeSolverTolerance": obj.get("eigenmodeSolverTolerance"),
            "eigenmodeSolverMaxIterations": obj.get("eigenmodeSolverMaxIterations"),
            "targetFrequency": obj.get("targetFrequency"),
            "numericalJacobian": obj.get("numericalJacobian"),
            "fieldInitializations": [FieldInitialization.from_dict(_item) for _item in obj["fieldInitializations"]] if obj.get("fieldInitializations") is not None else None
        })
        return _obj


