# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SimulationInputFileType(str, Enum):
    """
    SimulationInputFileType
    """

    """
    allowed enum values
    """
    EXTRAINPUTFILE = 'extraInputFile'
    SIMULATIONOUTPUTDATABASE = 'simulationOutputDatabase'
    SIMULATIONOUTPUTFILE = 'simulationOutputFile'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SimulationInputFileType from a JSON string"""
        return cls(json.loads(json_str))


