# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from allsolve_rawapi.models.custom_script_section_name import CustomScriptSectionName
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SimulationScript(BaseModel):
    """
    SimulationScript
    """ # noqa: E501
    id: StrictStr = Field(description="Script ID")
    origin: Optional[StrictStr] = Field(default=None, description="Id of the original script if this is a copy.")
    main_script: StrictBool = Field(description="Is this script the main script of this simulation. Main script is the entry point and user can manually add imports to other scripts from there.", alias="mainScript")
    name: StrictStr = Field(description="Script user defined name")
    script: StrictStr = Field(description="Script content")
    modified_at: datetime = Field(description="Last script save date-time", alias="modifiedAt")
    section_name: Optional[CustomScriptSectionName] = Field(default=None, alias="sectionName")
    __properties: ClassVar[List[str]] = ["id", "origin", "mainScript", "name", "script", "modifiedAt", "sectionName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulationScript from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulationScript from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "origin": obj.get("origin"),
            "mainScript": obj.get("mainScript"),
            "name": obj.get("name"),
            "script": obj.get("script"),
            "modifiedAt": obj.get("modifiedAt"),
            "sectionName": obj.get("sectionName")
        })
        return _obj


