# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.simulation_input_file_type import SimulationInputFileType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SimulationInputFile(BaseModel):
    """
    SimulationInputFile
    """ # noqa: E501
    id: StrictStr
    type: SimulationInputFileType
    source_extra_input_file_id: Optional[StrictStr] = Field(default=None, description="Id of the extra input file if type is extraInputFile.", alias="sourceExtraInputFileId")
    source_simulation_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="sourceSimulationId")
    source_sweep_step: Optional[StrictInt] = Field(default=None, description="Sweep step if type is simulationOutputDatabase or simulationOutputFile in case the source simulation is a sweep. ", alias="sourceSweepStep")
    source_file_name: Optional[StrictStr] = Field(default=None, description="File name if type is simulationOutputFile.", alias="sourceFileName")
    target_sweep_step: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Optional sweep step index. Null means all sweep steps.", alias="targetSweepStep")
    target_rank: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Optional rank index. Null means all ranks.", alias="targetRank")
    target_file_name: Optional[StrictStr] = Field(default=None, description="File name if type is simulationOutputDatabase or simulationOutputFile. For extraInputFile the name is the extra input file's name. ", alias="targetFileName")
    __properties: ClassVar[List[str]] = ["id", "type", "sourceExtraInputFileId", "sourceSimulationId", "sourceSweepStep", "sourceFileName", "targetSweepStep", "targetRank", "targetFileName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulationInputFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulationInputFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "sourceExtraInputFileId": obj.get("sourceExtraInputFileId"),
            "sourceSimulationId": obj.get("sourceSimulationId"),
            "sourceSweepStep": obj.get("sourceSweepStep"),
            "sourceFileName": obj.get("sourceFileName"),
            "targetSweepStep": obj.get("targetSweepStep"),
            "targetRank": obj.get("targetRank"),
            "targetFileName": obj.get("targetFileName")
        })
        return _obj


