# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from allsolve_rawapi.models.entity_selection import EntitySelection
from allsolve_rawapi.models.extrusion_layer_definition import ExtrusionLayerDefinition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SlantedExtrusion(BaseModel):
    """
    Slanted mesh extrusion specification
    """ # noqa: E501
    volumes: EntitySelection
    from_surfaces: EntitySelection = Field(alias="fromSurfaces")
    to_surfaces: EntitySelection = Field(alias="toSurfaces")
    layers: Annotated[List[ExtrusionLayerDefinition], Field(min_length=1)] = Field(description="Extrusion layer definitions for an extrusion layer. The relativeHeight values will be used to calculate the relative height of each of the sublayers. ")
    quadrangles: StrictBool = Field(description="Generate quadrangles in the side walls of the extrusion instead of triangles.")
    __properties: ClassVar[List[str]] = ["volumes", "fromSurfaces", "toSurfaces", "layers", "quadrangles"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlantedExtrusion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of volumes
        if self.volumes:
            _dict['volumes'] = self.volumes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of from_surfaces
        if self.from_surfaces:
            _dict['fromSurfaces'] = self.from_surfaces.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_surfaces
        if self.to_surfaces:
            _dict['toSurfaces'] = self.to_surfaces.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in layers (list)
        _items = []
        if self.layers:
            for _item_layers in self.layers:
                if _item_layers:
                    _items.append(_item_layers.to_dict())
            _dict['layers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlantedExtrusion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "volumes": EntitySelection.from_dict(obj["volumes"]) if obj.get("volumes") is not None else None,
            "fromSurfaces": EntitySelection.from_dict(obj["fromSurfaces"]) if obj.get("fromSurfaces") is not None else None,
            "toSurfaces": EntitySelection.from_dict(obj["toSurfaces"]) if obj.get("toSurfaces") is not None else None,
            "layers": [ExtrusionLayerDefinition.from_dict(_item) for _item in obj["layers"]] if obj.get("layers") is not None else None,
            "quadrangles": obj.get("quadrangles") if obj.get("quadrangles") is not None else False
        })
        return _obj


