# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SolverPrecision(str, Enum):
    """
    Precision of the solver. - double (default) - use the double precision floating point (64 bits) - quadruple        - use the quadruple precision floating point (128 bits) 
    """

    """
    allowed enum values
    """
    DOUBLE = 'double'
    QUADRUPLE = 'quadruple'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SolverPrecision from a JSON string"""
        return cls(json.loads(json_str))


