# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allsolve_rawapi.models.flatten_and_rebuild_extrusion import FlattenAndRebuildExtrusion
from allsolve_rawapi.models.path_extrusion import PathExtrusion
from allsolve_rawapi.models.slanted_extrusion import SlantedExtrusion
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StructuredMeshDefinitions(BaseModel):
    """
    Structured mesh specifications (slanted extrusions, extrusions along a path, extruded mesh v3) 
    """ # noqa: E501
    slanted_extrusions: Optional[Annotated[List[SlantedExtrusion], Field(min_length=1)]] = Field(default=None, description="Slanted mesh extrusion specifications", alias="slantedExtrusions")
    path_extrusions: Optional[Annotated[List[PathExtrusion], Field(min_length=1)]] = Field(default=None, description="Path mesh extrusion specifications", alias="pathExtrusions")
    flatten_and_rebuild_extrusions: Optional[Annotated[List[FlattenAndRebuildExtrusion], Field(min_length=1)]] = Field(default=None, description="Flatten-and-rebuild extrusions.", alias="flattenAndRebuildExtrusions")
    __properties: ClassVar[List[str]] = ["slantedExtrusions", "pathExtrusions", "flattenAndRebuildExtrusions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredMeshDefinitions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in slanted_extrusions (list)
        _items = []
        if self.slanted_extrusions:
            for _item_slanted_extrusions in self.slanted_extrusions:
                if _item_slanted_extrusions:
                    _items.append(_item_slanted_extrusions.to_dict())
            _dict['slantedExtrusions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in path_extrusions (list)
        _items = []
        if self.path_extrusions:
            for _item_path_extrusions in self.path_extrusions:
                if _item_path_extrusions:
                    _items.append(_item_path_extrusions.to_dict())
            _dict['pathExtrusions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in flatten_and_rebuild_extrusions (list)
        _items = []
        if self.flatten_and_rebuild_extrusions:
            for _item_flatten_and_rebuild_extrusions in self.flatten_and_rebuild_extrusions:
                if _item_flatten_and_rebuild_extrusions:
                    _items.append(_item_flatten_and_rebuild_extrusions.to_dict())
            _dict['flattenAndRebuildExtrusions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredMeshDefinitions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slantedExtrusions": [SlantedExtrusion.from_dict(_item) for _item in obj["slantedExtrusions"]] if obj.get("slantedExtrusions") is not None else None,
            "pathExtrusions": [PathExtrusion.from_dict(_item) for _item in obj["pathExtrusions"]] if obj.get("pathExtrusions") is not None else None,
            "flattenAndRebuildExtrusions": [FlattenAndRebuildExtrusion.from_dict(_item) for _item in obj["flattenAndRebuildExtrusions"]] if obj.get("flattenAndRebuildExtrusions") is not None else None
        })
        return _obj


