# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from allsolve_rawapi.models.structured_curve_segment import StructuredCurveSegment
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StructuredMeshing(BaseModel):
    """
    Structured mesh configuration for the model
    """ # noqa: E501
    structured_curves: List[StructuredCurveSegment] = Field(description="List of structured curve configurations", alias="structuredCurves")
    __properties: ClassVar[List[str]] = ["structuredCurves"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredMeshing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in structured_curves (list)
        _items = []
        if self.structured_curves:
            for _item_structured_curves in self.structured_curves:
                if _item_structured_curves:
                    _items.append(_item_structured_curves.to_dict())
            _dict['structuredCurves'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredMeshing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "structuredCurves": [StructuredCurveSegment.from_dict(_item) for _item in obj["structuredCurves"]] if obj.get("structuredCurves") is not None else None
        })
        return _obj


