# coding: utf-8

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SweepType(str, Enum):
    """
    Sweep generation mode for override sets with type \"sweep\". - cartesian_product: Generate all combinations of variable arrays (rightmost variable changes fastest) - specific_values: Arrays must match length, values paired by index (legacy behavior) 
    """

    """
    allowed enum values
    """
    CARTESIAN_PRODUCT = 'cartesian_product'
    SPECIFIC_VALUES = 'specific_values'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SweepType from a JSON string"""
        return cls(json.loads(json_str))


