# coding: utf-8

# flake8: noqa

"""
    Public API

    Quanscient Allsolve Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnalysisType",
    "AttributePath",
    "AttributePathItem",
    "AutoTransfiniteElementSizes",
    "AutoTransfiniteEntry",
    "CadAlignment",
    "CadAngle",
    "CadAngularUnit",
    "CadAttribute",
    "CadBasicGeometry",
    "CadBoolean",
    "CadBooleanElements",
    "CadBooleanOperation",
    "CadBooleanOperationType",
    "CadBox",
    "CadCone",
    "CadCreateGdsLayersRequest",
    "CadCylinder",
    "CadDisk",
    "CadDistance",
    "CadDistanceUnit",
    "CadEnclosingOperation",
    "CadEntity",
    "CadEulerAngles",
    "CadFileDefinition",
    "CadGdsExtrudeParameters",
    "CadGdsImportConfig",
    "CadGdsLayer",
    "CadGdsUnifyLayerDiscretizations",
    "CadGeometryDefinition",
    "CadGeometryElement",
    "CadGlobEnum",
    "CadGridParameters",
    "CadImportConfig",
    "CadImportType",
    "CadLine",
    "CadMetadataOperation",
    "CadMetadataOperationType",
    "CadPathSegment",
    "CadPositiveInteger",
    "CadRectangle",
    "CadRemoveEntityOperation",
    "CadRotateParameters",
    "CadScalar",
    "CadSphere",
    "CadSplineMethod",
    "CadSurfaceRectangle",
    "CadTorus",
    "CadTransformOperation",
    "CadTranslateParameters",
    "CadUnitDefaults",
    "CadUnitDefaultsInput",
    "CadVector",
    "CadWedge",
    "CopyRequest",
    "CustomScriptSectionName",
    "DisabledScriptSection",
    "DistributedSolverMode",
    "EntitySelection",
    "EntityType",
    "ErrorResponse",
    "ExpressionBoundingBox",
    "ExpressionShape",
    "ExpressionVector",
    "ExtrusionLayerDefinition",
    "ExtrusionOverlapMode",
    "FieldInitialization",
    "FieldInitializationType",
    "FieldInitializationUpdate",
    "FileDownloadUrl",
    "FileUploadCompletedPart",
    "FileUploadCompletion",
    "FileUploadUrls",
    "FlattenAndRebuildExtrusion",
    "GDSImportConfig",
    "GDSLayer",
    "GeneratedSimulationScripts",
    "GeoFileImport",
    "GeometryElement",
    "GeometryElementUpdate",
    "GeometryFileType",
    "GeometryPipelineVersion",
    "GeometryProcessingStartResponse",
    "GeometryUnit",
    "HealthResponse",
    "InputFile",
    "InputModelUrls",
    "Interaction",
    "InteractionParameter",
    "InteractionTarget",
    "InteractionUpdate",
    "Job",
    "JobData",
    "JobDataOverride",
    "JobLogEvent",
    "JobStatus",
    "JobStatusReason",
    "JobStatusType",
    "JobType",
    "LibraryOwnerType",
    "Material",
    "MaterialUpdate",
    "Mesh",
    "MeshAlgorithm",
    "MeshDensity",
    "MeshExtrusion",
    "MeshExtrusionType",
    "MeshFile",
    "MeshFileOverride",
    "MeshInstance",
    "MeshInstanceFile",
    "MeshMetrics",
    "MeshParameters",
    "MeshSupportData",
    "MeshUpdate",
    "MeshingError",
    "MeshingErrorCode",
    "MeshingErrors",
    "ModelField",
    "NewFileUpload",
    "NewGeoFileImport",
    "NewGeometryElement",
    "NewInteraction",
    "NewMaterial",
    "NewOverrideSet",
    "NewPhysics",
    "NewProject",
    "NewRegion",
    "OauthClientTokenGrantType",
    "OauthClientTokenResponse",
    "OrganizationQuota",
    "OverrideSet",
    "OverrideSetUpdate",
    "PMLSettings",
    "PathExtrusion",
    "PhysicalProperty",
    "PhysicalPropertyAlternativeDefinition",
    "PhysicalPropertyDefinition",
    "Physics",
    "PhysicsCreationResponse",
    "PhysicsDeletionResponse",
    "PhysicsField",
    "PhysicsUpdate",
    "Project",
    "ProjectListResult",
    "ProjectTypeFilter",
    "PythonScript",
    "PythonScriptCustomSection",
    "PythonScriptImport",
    "PythonScriptSection",
    "Region",
    "RegionRule",
    "RegionRuleOperation",
    "RegionSelector",
    "RegionUpdate",
    "STEPImportConfig",
    "SelectiveMeshRefinement",
    "SelectiveMeshRefinementItem",
    "SharedExpression",
    "SharedExpressionArg",
    "SharedExpressionOverride",
    "SharedExpressionOverrideType",
    "SharedExpressionOverrideUpdate",
    "SharedExpressionOwnerType",
    "SharedExpressionType",
    "SharedExpressionUpdate",
    "Simulation",
    "SimulationInputFile",
    "SimulationInputFileType",
    "SimulationInputFileUpdateResponse",
    "SimulationScript",
    "SimulationScriptUpdate",
    "SimulationUpdate",
    "SlantedExtrusion",
    "SolverPrecision",
    "StructuredCurveSegment",
    "StructuredMeshDefinitions",
    "StructuredMeshEntity",
    "StructuredMeshing",
    "SweepType",
    "TimestepAlgorithm",
]

# import apis into sdk package
from allsolve_rawapi.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from allsolve_rawapi.api_response import ApiResponse as ApiResponse
from allsolve_rawapi.api_client import ApiClient as ApiClient
from allsolve_rawapi.configuration import Configuration as Configuration
from allsolve_rawapi.exceptions import OpenApiException as OpenApiException
from allsolve_rawapi.exceptions import ApiTypeError as ApiTypeError
from allsolve_rawapi.exceptions import ApiValueError as ApiValueError
from allsolve_rawapi.exceptions import ApiKeyError as ApiKeyError
from allsolve_rawapi.exceptions import ApiAttributeError as ApiAttributeError
from allsolve_rawapi.exceptions import ApiException as ApiException

# import models into sdk package
from allsolve_rawapi.models.analysis_type import AnalysisType as AnalysisType
from allsolve_rawapi.models.attribute_path import AttributePath as AttributePath
from allsolve_rawapi.models.attribute_path_item import AttributePathItem as AttributePathItem
from allsolve_rawapi.models.auto_transfinite_element_sizes import AutoTransfiniteElementSizes as AutoTransfiniteElementSizes
from allsolve_rawapi.models.auto_transfinite_entry import AutoTransfiniteEntry as AutoTransfiniteEntry
from allsolve_rawapi.models.cad_alignment import CadAlignment as CadAlignment
from allsolve_rawapi.models.cad_angle import CadAngle as CadAngle
from allsolve_rawapi.models.cad_angular_unit import CadAngularUnit as CadAngularUnit
from allsolve_rawapi.models.cad_attribute import CadAttribute as CadAttribute
from allsolve_rawapi.models.cad_basic_geometry import CadBasicGeometry as CadBasicGeometry
from allsolve_rawapi.models.cad_boolean import CadBoolean as CadBoolean
from allsolve_rawapi.models.cad_boolean_elements import CadBooleanElements as CadBooleanElements
from allsolve_rawapi.models.cad_boolean_operation import CadBooleanOperation as CadBooleanOperation
from allsolve_rawapi.models.cad_boolean_operation_type import CadBooleanOperationType as CadBooleanOperationType
from allsolve_rawapi.models.cad_box import CadBox as CadBox
from allsolve_rawapi.models.cad_cone import CadCone as CadCone
from allsolve_rawapi.models.cad_create_gds_layers_request import CadCreateGdsLayersRequest as CadCreateGdsLayersRequest
from allsolve_rawapi.models.cad_cylinder import CadCylinder as CadCylinder
from allsolve_rawapi.models.cad_disk import CadDisk as CadDisk
from allsolve_rawapi.models.cad_distance import CadDistance as CadDistance
from allsolve_rawapi.models.cad_distance_unit import CadDistanceUnit as CadDistanceUnit
from allsolve_rawapi.models.cad_enclosing_operation import CadEnclosingOperation as CadEnclosingOperation
from allsolve_rawapi.models.cad_entity import CadEntity as CadEntity
from allsolve_rawapi.models.cad_euler_angles import CadEulerAngles as CadEulerAngles
from allsolve_rawapi.models.cad_file_definition import CadFileDefinition as CadFileDefinition
from allsolve_rawapi.models.cad_gds_extrude_parameters import CadGdsExtrudeParameters as CadGdsExtrudeParameters
from allsolve_rawapi.models.cad_gds_import_config import CadGdsImportConfig as CadGdsImportConfig
from allsolve_rawapi.models.cad_gds_layer import CadGdsLayer as CadGdsLayer
from allsolve_rawapi.models.cad_gds_unify_layer_discretizations import CadGdsUnifyLayerDiscretizations as CadGdsUnifyLayerDiscretizations
from allsolve_rawapi.models.cad_geometry_definition import CadGeometryDefinition as CadGeometryDefinition
from allsolve_rawapi.models.cad_geometry_element import CadGeometryElement as CadGeometryElement
from allsolve_rawapi.models.cad_glob_enum import CadGlobEnum as CadGlobEnum
from allsolve_rawapi.models.cad_grid_parameters import CadGridParameters as CadGridParameters
from allsolve_rawapi.models.cad_import_config import CadImportConfig as CadImportConfig
from allsolve_rawapi.models.cad_import_type import CadImportType as CadImportType
from allsolve_rawapi.models.cad_line import CadLine as CadLine
from allsolve_rawapi.models.cad_metadata_operation import CadMetadataOperation as CadMetadataOperation
from allsolve_rawapi.models.cad_metadata_operation_type import CadMetadataOperationType as CadMetadataOperationType
from allsolve_rawapi.models.cad_path_segment import CadPathSegment as CadPathSegment
from allsolve_rawapi.models.cad_positive_integer import CadPositiveInteger as CadPositiveInteger
from allsolve_rawapi.models.cad_rectangle import CadRectangle as CadRectangle
from allsolve_rawapi.models.cad_remove_entity_operation import CadRemoveEntityOperation as CadRemoveEntityOperation
from allsolve_rawapi.models.cad_rotate_parameters import CadRotateParameters as CadRotateParameters
from allsolve_rawapi.models.cad_scalar import CadScalar as CadScalar
from allsolve_rawapi.models.cad_sphere import CadSphere as CadSphere
from allsolve_rawapi.models.cad_spline_method import CadSplineMethod as CadSplineMethod
from allsolve_rawapi.models.cad_surface_rectangle import CadSurfaceRectangle as CadSurfaceRectangle
from allsolve_rawapi.models.cad_torus import CadTorus as CadTorus
from allsolve_rawapi.models.cad_transform_operation import CadTransformOperation as CadTransformOperation
from allsolve_rawapi.models.cad_translate_parameters import CadTranslateParameters as CadTranslateParameters
from allsolve_rawapi.models.cad_unit_defaults import CadUnitDefaults as CadUnitDefaults
from allsolve_rawapi.models.cad_unit_defaults_input import CadUnitDefaultsInput as CadUnitDefaultsInput
from allsolve_rawapi.models.cad_vector import CadVector as CadVector
from allsolve_rawapi.models.cad_wedge import CadWedge as CadWedge
from allsolve_rawapi.models.copy_request import CopyRequest as CopyRequest
from allsolve_rawapi.models.custom_script_section_name import CustomScriptSectionName as CustomScriptSectionName
from allsolve_rawapi.models.disabled_script_section import DisabledScriptSection as DisabledScriptSection
from allsolve_rawapi.models.distributed_solver_mode import DistributedSolverMode as DistributedSolverMode
from allsolve_rawapi.models.entity_selection import EntitySelection as EntitySelection
from allsolve_rawapi.models.entity_type import EntityType as EntityType
from allsolve_rawapi.models.error_response import ErrorResponse as ErrorResponse
from allsolve_rawapi.models.expression_bounding_box import ExpressionBoundingBox as ExpressionBoundingBox
from allsolve_rawapi.models.expression_shape import ExpressionShape as ExpressionShape
from allsolve_rawapi.models.expression_vector import ExpressionVector as ExpressionVector
from allsolve_rawapi.models.extrusion_layer_definition import ExtrusionLayerDefinition as ExtrusionLayerDefinition
from allsolve_rawapi.models.extrusion_overlap_mode import ExtrusionOverlapMode as ExtrusionOverlapMode
from allsolve_rawapi.models.field_initialization import FieldInitialization as FieldInitialization
from allsolve_rawapi.models.field_initialization_type import FieldInitializationType as FieldInitializationType
from allsolve_rawapi.models.field_initialization_update import FieldInitializationUpdate as FieldInitializationUpdate
from allsolve_rawapi.models.file_download_url import FileDownloadUrl as FileDownloadUrl
from allsolve_rawapi.models.file_upload_completed_part import FileUploadCompletedPart as FileUploadCompletedPart
from allsolve_rawapi.models.file_upload_completion import FileUploadCompletion as FileUploadCompletion
from allsolve_rawapi.models.file_upload_urls import FileUploadUrls as FileUploadUrls
from allsolve_rawapi.models.flatten_and_rebuild_extrusion import FlattenAndRebuildExtrusion as FlattenAndRebuildExtrusion
from allsolve_rawapi.models.gds_import_config import GDSImportConfig as GDSImportConfig
from allsolve_rawapi.models.gds_layer import GDSLayer as GDSLayer
from allsolve_rawapi.models.generated_simulation_scripts import GeneratedSimulationScripts as GeneratedSimulationScripts
from allsolve_rawapi.models.geo_file_import import GeoFileImport as GeoFileImport
from allsolve_rawapi.models.geometry_element import GeometryElement as GeometryElement
from allsolve_rawapi.models.geometry_element_update import GeometryElementUpdate as GeometryElementUpdate
from allsolve_rawapi.models.geometry_file_type import GeometryFileType as GeometryFileType
from allsolve_rawapi.models.geometry_pipeline_version import GeometryPipelineVersion as GeometryPipelineVersion
from allsolve_rawapi.models.geometry_processing_start_response import GeometryProcessingStartResponse as GeometryProcessingStartResponse
from allsolve_rawapi.models.geometry_unit import GeometryUnit as GeometryUnit
from allsolve_rawapi.models.health_response import HealthResponse as HealthResponse
from allsolve_rawapi.models.input_file import InputFile as InputFile
from allsolve_rawapi.models.input_model_urls import InputModelUrls as InputModelUrls
from allsolve_rawapi.models.interaction import Interaction as Interaction
from allsolve_rawapi.models.interaction_parameter import InteractionParameter as InteractionParameter
from allsolve_rawapi.models.interaction_target import InteractionTarget as InteractionTarget
from allsolve_rawapi.models.interaction_update import InteractionUpdate as InteractionUpdate
from allsolve_rawapi.models.job import Job as Job
from allsolve_rawapi.models.job_data import JobData as JobData
from allsolve_rawapi.models.job_data_override import JobDataOverride as JobDataOverride
from allsolve_rawapi.models.job_log_event import JobLogEvent as JobLogEvent
from allsolve_rawapi.models.job_status import JobStatus as JobStatus
from allsolve_rawapi.models.job_status_reason import JobStatusReason as JobStatusReason
from allsolve_rawapi.models.job_status_type import JobStatusType as JobStatusType
from allsolve_rawapi.models.job_type import JobType as JobType
from allsolve_rawapi.models.library_owner_type import LibraryOwnerType as LibraryOwnerType
from allsolve_rawapi.models.material import Material as Material
from allsolve_rawapi.models.material_update import MaterialUpdate as MaterialUpdate
from allsolve_rawapi.models.mesh import Mesh as Mesh
from allsolve_rawapi.models.mesh_algorithm import MeshAlgorithm as MeshAlgorithm
from allsolve_rawapi.models.mesh_density import MeshDensity as MeshDensity
from allsolve_rawapi.models.mesh_extrusion import MeshExtrusion as MeshExtrusion
from allsolve_rawapi.models.mesh_extrusion_type import MeshExtrusionType as MeshExtrusionType
from allsolve_rawapi.models.mesh_file import MeshFile as MeshFile
from allsolve_rawapi.models.mesh_file_override import MeshFileOverride as MeshFileOverride
from allsolve_rawapi.models.mesh_instance import MeshInstance as MeshInstance
from allsolve_rawapi.models.mesh_instance_file import MeshInstanceFile as MeshInstanceFile
from allsolve_rawapi.models.mesh_metrics import MeshMetrics as MeshMetrics
from allsolve_rawapi.models.mesh_parameters import MeshParameters as MeshParameters
from allsolve_rawapi.models.mesh_support_data import MeshSupportData as MeshSupportData
from allsolve_rawapi.models.mesh_update import MeshUpdate as MeshUpdate
from allsolve_rawapi.models.meshing_error import MeshingError as MeshingError
from allsolve_rawapi.models.meshing_error_code import MeshingErrorCode as MeshingErrorCode
from allsolve_rawapi.models.meshing_errors import MeshingErrors as MeshingErrors
from allsolve_rawapi.models.model_field import ModelField as ModelField
from allsolve_rawapi.models.new_file_upload import NewFileUpload as NewFileUpload
from allsolve_rawapi.models.new_geo_file_import import NewGeoFileImport as NewGeoFileImport
from allsolve_rawapi.models.new_geometry_element import NewGeometryElement as NewGeometryElement
from allsolve_rawapi.models.new_interaction import NewInteraction as NewInteraction
from allsolve_rawapi.models.new_material import NewMaterial as NewMaterial
from allsolve_rawapi.models.new_override_set import NewOverrideSet as NewOverrideSet
from allsolve_rawapi.models.new_physics import NewPhysics as NewPhysics
from allsolve_rawapi.models.new_project import NewProject as NewProject
from allsolve_rawapi.models.new_region import NewRegion as NewRegion
from allsolve_rawapi.models.oauth_client_token_grant_type import OauthClientTokenGrantType as OauthClientTokenGrantType
from allsolve_rawapi.models.oauth_client_token_response import OauthClientTokenResponse as OauthClientTokenResponse
from allsolve_rawapi.models.organization_quota import OrganizationQuota as OrganizationQuota
from allsolve_rawapi.models.override_set import OverrideSet as OverrideSet
from allsolve_rawapi.models.override_set_update import OverrideSetUpdate as OverrideSetUpdate
from allsolve_rawapi.models.pml_settings import PMLSettings as PMLSettings
from allsolve_rawapi.models.path_extrusion import PathExtrusion as PathExtrusion
from allsolve_rawapi.models.physical_property import PhysicalProperty as PhysicalProperty
from allsolve_rawapi.models.physical_property_alternative_definition import PhysicalPropertyAlternativeDefinition as PhysicalPropertyAlternativeDefinition
from allsolve_rawapi.models.physical_property_definition import PhysicalPropertyDefinition as PhysicalPropertyDefinition
from allsolve_rawapi.models.physics import Physics as Physics
from allsolve_rawapi.models.physics_creation_response import PhysicsCreationResponse as PhysicsCreationResponse
from allsolve_rawapi.models.physics_deletion_response import PhysicsDeletionResponse as PhysicsDeletionResponse
from allsolve_rawapi.models.physics_field import PhysicsField as PhysicsField
from allsolve_rawapi.models.physics_update import PhysicsUpdate as PhysicsUpdate
from allsolve_rawapi.models.project import Project as Project
from allsolve_rawapi.models.project_list_result import ProjectListResult as ProjectListResult
from allsolve_rawapi.models.project_type_filter import ProjectTypeFilter as ProjectTypeFilter
from allsolve_rawapi.models.python_script import PythonScript as PythonScript
from allsolve_rawapi.models.python_script_custom_section import PythonScriptCustomSection as PythonScriptCustomSection
from allsolve_rawapi.models.python_script_import import PythonScriptImport as PythonScriptImport
from allsolve_rawapi.models.python_script_section import PythonScriptSection as PythonScriptSection
from allsolve_rawapi.models.region import Region as Region
from allsolve_rawapi.models.region_rule import RegionRule as RegionRule
from allsolve_rawapi.models.region_rule_operation import RegionRuleOperation as RegionRuleOperation
from allsolve_rawapi.models.region_selector import RegionSelector as RegionSelector
from allsolve_rawapi.models.region_update import RegionUpdate as RegionUpdate
from allsolve_rawapi.models.step_import_config import STEPImportConfig as STEPImportConfig
from allsolve_rawapi.models.selective_mesh_refinement import SelectiveMeshRefinement as SelectiveMeshRefinement
from allsolve_rawapi.models.selective_mesh_refinement_item import SelectiveMeshRefinementItem as SelectiveMeshRefinementItem
from allsolve_rawapi.models.shared_expression import SharedExpression as SharedExpression
from allsolve_rawapi.models.shared_expression_arg import SharedExpressionArg as SharedExpressionArg
from allsolve_rawapi.models.shared_expression_override import SharedExpressionOverride as SharedExpressionOverride
from allsolve_rawapi.models.shared_expression_override_type import SharedExpressionOverrideType as SharedExpressionOverrideType
from allsolve_rawapi.models.shared_expression_override_update import SharedExpressionOverrideUpdate as SharedExpressionOverrideUpdate
from allsolve_rawapi.models.shared_expression_owner_type import SharedExpressionOwnerType as SharedExpressionOwnerType
from allsolve_rawapi.models.shared_expression_type import SharedExpressionType as SharedExpressionType
from allsolve_rawapi.models.shared_expression_update import SharedExpressionUpdate as SharedExpressionUpdate
from allsolve_rawapi.models.simulation import Simulation as Simulation
from allsolve_rawapi.models.simulation_input_file import SimulationInputFile as SimulationInputFile
from allsolve_rawapi.models.simulation_input_file_type import SimulationInputFileType as SimulationInputFileType
from allsolve_rawapi.models.simulation_input_file_update_response import SimulationInputFileUpdateResponse as SimulationInputFileUpdateResponse
from allsolve_rawapi.models.simulation_script import SimulationScript as SimulationScript
from allsolve_rawapi.models.simulation_script_update import SimulationScriptUpdate as SimulationScriptUpdate
from allsolve_rawapi.models.simulation_update import SimulationUpdate as SimulationUpdate
from allsolve_rawapi.models.slanted_extrusion import SlantedExtrusion as SlantedExtrusion
from allsolve_rawapi.models.solver_precision import SolverPrecision as SolverPrecision
from allsolve_rawapi.models.structured_curve_segment import StructuredCurveSegment as StructuredCurveSegment
from allsolve_rawapi.models.structured_mesh_definitions import StructuredMeshDefinitions as StructuredMeshDefinitions
from allsolve_rawapi.models.structured_mesh_entity import StructuredMeshEntity as StructuredMeshEntity
from allsolve_rawapi.models.structured_meshing import StructuredMeshing as StructuredMeshing
from allsolve_rawapi.models.sweep_type import SweepType as SweepType
from allsolve_rawapi.models.timestep_algorithm import TimestepAlgorithm as TimestepAlgorithm

